### ISSUE TITLE
multiple if conditions look terrible in VS Code after applying

### ISSUE THREAD

**Issue by wbern** [prettier/prettier-eslint#100]
**Versions**:

- `prettier-eslint` version: the one shipped in `prettier-eslint-vscode` for VS Code
- `node` version: 6.9.2
- `npm` (or `yarn`) version: 3.x.x

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

No

**Relevant code or config**

```
        if (!aboolean &&
            this &&
            (!this.caller ||
            this.caller === this ||
            !this.somevalue||
            this.caller === this.someobject.avalue)) {
            aboolean = true;
        }
```

**What I did:**

Pressed the keyboard shortcut to apply prettier-eslint fixes.

**What happened:**

It became like this:
```
        if (
            !aboolean&&
      this &&
      (!this.caller ||
        this.caller === this ||
        !this.somevalue||
        this.caller === this.someobject.value)
        ) {
            aboolean = true;
        }
```

**Reproduction repository:**

N/A

**Problem description:**

Is it possible for me to configure how lines should separate in my if conditions?

**Comment by kentcdodds** [comment]
Hi! This is very strange! Please follow the debugging tips and let me know what your find 👍

**Comment by wbern** [comment]
@kentcdodds The issue lies with the vs code extension I found. See https://github.com/RobinMalfait/prettier-eslint-code/issues/27

**Comment by kentcdodds** [comment]
Thanks for digging 👍

I'll close this issue then!
