### ISSUE TITLE
Can I override prettier way of formatting with Prettier-ESlint?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier-eslint#106]
Prettier format the code in specific ways, I like some but not all formatting in all cases.

With help of this tool can I change that formatting and auto-fix too with ESLint overrides?

**Comment by kentcdodds** [comment]
Yes, eslint formatting runs after prettier, so you could add plugins which format it the way you like. If they don't exist, you could [write one](https://youtu.be/CFQBHy8RCpg)
