### ISSUE TITLE
Extends Options

### ISSUE THREAD

**Issue by arb** [prettier/prettier-eslint#109]
**Versions**:

- `prettier-eslint` version: 6.4.2
- `node` version: 7.6.0
- `npm` (or `yarn`) version: 4.4.1

**Problem description:**

How do I extend this eslint configuration? I want to be able to add an .eslitrc.json file that says something like 

```json
{
  "extends": "prettier-eslint"
}
```

Visual Studio complains that this config can't be found and I agree, I don't see an .eslint file anywhere I can extend.

**Comment by kentcdodds** [comment]
Hi @arb,
`prettier-eslint` is not an eslint config you can extend. It's a tool that integrates prettier and eslint together. If you are looking for a config, try [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

Good luck!
