### ISSUE TITLE
Support prettier config file

### ISSUE THREAD

**Issue by zimme** [prettier/prettier-eslint#110]
Hey,

Now that prettier/prettier#2434 is merged, would we need to do anything in this package to support prettier's config file?

**Comment by zimme** [comment]
I guess we would need to not send in prettier options if we detect any of the valid configuration files?

**Comment by kentcdodds** [comment]
Hmmm... Interesting! I hadn't noticed this! Does prettier's node API search for the config? I'd definitely prefer to avoid looking for it ourselves if prettier can find it for us.

**Comment by zimme** [comment]
Prettier uses `cosmiconfig` to find the configuration files.

**Comment by zimme** [comment]
They seem to be exporting a `resoveConfig` function which sets `preocess.exitCode = 2` on error resolving the config. So I guess that could be used to check if there is a config file in the project?

**Comment by zimme** [comment]
Also this isn't released yet, but as the PR was merged now I thought it was a good time to start talking about what's needed over here to get it working once it's released =)

**Comment by kentcdodds** [comment]
Sounds good. Thanks for looking into this and bringing it up! Could you make a PR?

**Comment by zimme** [comment]
I don't think I'll have time do put together a PR until August, homestretch at work before my vacation coming up on Friday.

But if it hasn't been resolved and I have time to spare, I'll try and put a PR together.

**Comment by kentcdodds** [comment]
Cool, I'll tweet about it and we'll see if anyone else is interested.

Anyone else: If you're interested, just comment here when you're ready to start working on it. Thanks!

**Comment by NamPNQ** [comment]
I think I can take care this issue

**Comment by kentcdodds** [comment]
Awesome!

**Comment by charlike** [comment]
The most correct thing is to do nothing. This jobs should be done in prettier itself automagically. If currently not working (didn't tried it) it probably because they uses the resolving only in the CLI part of the whole package, not in the API/main function or etc, which is the correct move. Btw, didn't even look their code, hm... yea didn't have time last months.

**Comment by zimme** [comment]
Closing this in favour of #114.
