### ISSUE TITLE
Can't make the gulp wrapper to run successfully.

### ISSUE THREAD

**Issue by sorioinc** [prettier/prettier-eslint#112]
Hello,

I was trying to use the gulp sample but can't make it work. I get this error: `TypeError: Cannot read property 'logLevel' of undefined`. Even if I send an empty options object (for it to find the default log level):
```shell
.pipe(prettierEslint({}))
```
It shows another error: `TypeError: path must be a string or Buffer`. What I'm I doing wrong?

**Comment by kentcdodds** [comment]
I haven't used gulp in quite a while, but I'm pretty sure whatever you put into `pipe` needs to be a function that accepts a stream or something. In any case `prettier-eslint` doesn't directly support `gulp`, but you might take inspiration from [`gulp-prettier`](https://github.com/bhargavrpatel/gulp-prettier/blob/master/index.js). You can pretty much copy that and swap `require('prettier')` with `require('prettier-eslint')` and update the callsite to reflect prettier-eslint's API and you should be set.

**Comment by kentcdodds** [comment]
Good luck! :smile:

**Comment by sorioinc** [comment]
Thanks for the suggestion @kentcdodds, I created a fork of `gulp-prettier`. Maybe it can be useful to someone else. [gulp-prettier-eslint]:https://www.npmjs.com/package/gulp-prettier-eslint

**Comment by kentcdodds** [comment]
Cool! Thanks!

**Comment by kentcdodds** [comment]
Actually, would you like to add a link to this in the README?
