### ISSUE TITLE
Errors while integration: no-confusing-arrow & max-len with react and {' '} space before a tag

### ISSUE THREAD

**Issue by bertho-zero** [prettier/prettier-eslint#113]
**Versions**:

- `prettier-eslint` version: 4.1.1
- `node` version: 8.0.0
- `npm` version: 4.6.1

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**What I did:**

After I lauchend `./node_modules/.bin/eslint --print-config .eslintrc.js | ./node_modules/.bin/prettier-eslint --trailing-comma none --write ./src/**/*.js` in [my project](https://github.com/bertho-zero/react-redux-universal-hot-example), I get errors when running `./node_modules/.bin/eslint -c .eslintrc src`

**What happened:**

```
/home/bertho/dev/react-redux-universal-hot-example/src/containers/About/About.js
  9:14  error  Arrow function used ambiguously with a conditional expression  no-confusing-arrow

/home/bertho/dev/react-redux-universal-hot-example/src/containers/Widgets/Widgets.js
  66:1   error  Line 66 exceeds the maximum line length of 120                 max-len
  90:17  error  Arrow function used ambiguously with a conditional expression  no-confusing-arrow
```

**Reproduction repository:**

https://github.com/bertho-zero/react-redux-universal-hot-example

**Comment by kentcdodds** [comment]
Your glob is expanded before it's given to prettier-eslint, please put it in quotes! Bash does funny things sometimes.

The reason for the `{' '}` is coming from prettier. In some situations it adds that to make the implicit space more explicit. You can play around with things more [here](https://prettier.io/).

Good luck!

**Comment by bertho-zero** [comment]
No, my glob is expanded by prettier-eslint, I have created an example here: [max-len example](https://prettier.io/playground/#%7B%22content%22%3A%22hello(%5C%22world%5C%22)%3B%5Cn%5Cn%5B%5Cn%20%20%5C%22lorem%5C%22%2C%5Cn%20%20%5C%22ipsum%5C%22%2C%5Cn%20%20%5C%22dolor%5C%22%2C%5Cn%20%20sit(%5C%22amet%5C%22)%2C%5Cn%20%20consectetur%5B%5C%22adipiscing%5C%22%5D%20%2B%20%5C%22elit%5C%22%5Cn%5D.reduce((first%2C%20second)%20%3D%3E%20first%20%2B%20second%2C%20%5C%22%5C%22)%3B%5Cn%5Cnconst%20Foo%20%3D%20(%7B%20bar%2C%20baz%2C%20things%20%7D)%20%3D%3E%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipiscing%20elit.%20Integer%20urna%5Cn%20%20%20%20%20%20sapien%2C%20efficitur%20in%20libero%20id%2C%20tincidunt%20maximus%20lectus.%20Duis%20id%5Cn%20%20%20%20%20%20consequat%20sem.%20Vestibulum%20nibh%20felis%2C%20finibus%20in%20egestas%20et%2C%20rutrum%20eu%5Cn%20%20%20%20%20%20orci.%20Mauris%20et%20neque%20congue%2C%20sagittis%20est%20at%2C%20suscipit%20ex.%20Maecenas%5Cn%20%20%20%20%20%20laoreet%20varius%20tincidunt.%20Vestibulum%20quis%20nibh%20dictum%20lacus%20dictum%5Cn%20%20%20%20%20%20eleifend%20ut%20eu%20elit.%20Nullam%20mauris%20lorem%2C%20eleifend%20ac%20libero%20et%2C%20viver%20%3Ccode%3Eragravida%20risus%3C%2Fcode%3E.%5Cn%20%20%20%20%20%20Curabitur%20vel%20lectus%20felis.%20Vivamus%20malesuada%20ipsum%20eget%5Cn%20%20%20%20%20%20leo%20tincidunt%20rutrum.%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

And do you know why the parentheses of certain arrow functions are removed? [no-confusing-arrow example](https://prettier.io/playground/#%7B%22content%22%3A%22const%20host%20%3D%20clientUrl%20%3D%3E%20(__SERVER__%20%3F%20%60http%3A%2F%2F%24%7Bconfig.apiHost%7D%3A%24%7Bconfig.apiPort%7D%60%20%3A%20clientUrl)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

**Comment by kentcdodds** [comment]
> And do you know why the parentheses of certain arrow functions are removed? [no-confusing-arrow example](https://prettier.io/playground/#%7B%22content%22%3A%22const%20host%20%3D%20clientUrl%20%3D%3E%20(__SERVER__%20%3F%20%60http%3A%2F%2F%24%7Bconfig.apiHost%7D%3A%24%7Bconfig.apiPort%7D%60%20%3A%20clientUrl)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

That's just the way prettier formats stuff. Nothing you can do about that unless you [write a custom ESLint rule](https://medium.com/@kentcdodds/fd6dd8076e26) that autofixes that.

> No, my glob is expanded by prettier-eslint

Hmmm... Well that's weird. If you could dig a little more to find the issue and suggest a solution that's welcome.

As for the `{' '}` that's added it's because when you add a line break between text and jsx, the only way to make sure that there's a space rendered is to include that.

**Comment by bertho-zero** [comment]
I added `"max-len": ["error", 120]` in my .eslintrc.

But [here](https://prettier.io/playground/#%7B%22content%22%3A%22import%20React%2C%20%7B%20Component%20%7D%20from%20'react'%3B%5Cnimport%20PropTypes%20from%20'prop-types'%3B%5Cnimport%20Helmet%20from%20'react-helmet'%3B%5Cnimport%20%7B%20connect%20%7D%20from%20'react-redux'%3B%5Cnimport%20*%20as%20widgetActions%20from%20'redux%2Fmodules%2Fwidgets'%3B%5Cnimport%20WidgetForm%20from%20'components%2FWidgetForm%2FWidgetForm'%3B%5Cnimport%20%7B%20asyncConnect%20%7D%20from%20'redux-connect'%3B%5Cn%5Cnconst%20%7B%20isLoaded%2C%20load%3A%20loadWidgets%20%7D%20%3D%20widgetActions%3B%5Cn%5Cn%40asyncConnect(%5B%7B%5Cn%20%20deferred%3A%20!!__SERVER__%2C%5Cn%20%20promise%3A%20(%7B%20store%3A%20%7B%20dispatch%2C%20getState%20%7D%20%7D)%20%3D%3E%20%7B%5Cn%20%20%20%20if%20(!isLoaded(getState()))%20%7B%5Cn%20%20%20%20%20%20return%20dispatch(loadWidgets())%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5D)%5Cn%40connect(%5Cn%20%20state%20%3D%3E%20(%7B%5Cn%20%20%20%20widgets%3A%20state.widgets.data%2C%5Cn%20%20%20%20editing%3A%20state.widgets.editing%2C%5Cn%20%20%20%20error%3A%20state.widgets.error%2C%5Cn%20%20%20%20loading%3A%20state.widgets.loading%5Cn%20%20%7D)%2C%5Cn%20%20%7B%20...widgetActions%20%7D)%5Cnexport%20default%20class%20Widgets%20extends%20Component%20%7B%5Cn%20%20static%20propTypes%20%3D%20%7B%5Cn%20%20%20%20widgets%3A%20PropTypes.array%2C%5Cn%20%20%20%20error%3A%20PropTypes.string%2C%5Cn%20%20%20%20loading%3A%20PropTypes.bool%2C%5Cn%20%20%20%20editing%3A%20PropTypes.object.isRequired%2C%5Cn%20%20%20%20load%3A%20PropTypes.func.isRequired%2C%5Cn%20%20%20%20editStart%3A%20PropTypes.func.isRequired%5Cn%20%20%7D%3B%5Cn%5Cn%20%20static%20defaultProps%20%3D%20%7B%5Cn%20%20%20%20widgets%3A%20null%2C%5Cn%20%20%20%20error%3A%20null%2C%5Cn%20%20%20%20loading%3A%20false%5Cn%20%20%7D%5Cn%5Cn%20%20render()%20%7B%5Cn%20%20%20%20const%20handleEdit%20%3D%20widget%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20const%20%7B%20editStart%20%7D%20%3D%20this.props%3B%5Cn%20%20%20%20%20%20return%20()%20%3D%3E%20editStart(String(widget.id))%3B%5Cn%20%20%20%20%7D%3B%5Cn%20%20%20%20const%20%7B%20widgets%2C%20error%2C%20editing%2C%20loading%2C%20load%20%7D%20%3D%20this.props%3B%5Cn%20%20%20%20const%20styles%20%3D%20require('.%2FWidgets.scss')%3B%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%3Cdiv%20className%3D%7B%60%24%7Bstyles.widgets%7D%20container%60%7D%3E%5Cn%20%20%20%20%20%20%20%20%3Ch1%3E%5Cn%20%20%20%20%20%20%20%20%20%20Widgets%5Cn%20%20%20%20%20%20%20%20%20%20%3Cbutton%20className%3D%7B%60%24%7Bstyles.refreshBtn%7D%20btn%20btn-success%60%7D%20onClick%3D%7Bload%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Ci%20className%3D%7B%60fa%20fa-refresh%20%24%7Bloading%20%3F%20'%20fa-spin'%20%3A%20''%7D%60%7D%20%2F%3E%7B'%20'%7DReload%20Widgets%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2Fbutton%3E%5Cn%20%20%20%20%20%20%20%20%3C%2Fh1%3E%5Cn%20%20%20%20%20%20%20%20%3CHelmet%20title%3D%5C%22Widgets%5C%22%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20%20%20If%20you%20hit%20refresh%20on%20your%20browser%2C%20the%20data%20loading%20will%20take%20place%20on%20the%20server%20before%20the%20page%20is%5Cn%20%20%20%20%20%20%20%20%20%20returned.%20If%20you%20navigated%20here%20from%20another%20page%2C%20the%20data%20was%20fetched%20from%20the%20client%20after%5Cn%20%20%20%20%20%20%20%20%20%20the%20route%20transition.%20This%20uses%20the%20decorator%20method%20%3Ccode%3E%40asyncConnect%3C%2Fcode%3E%20with%5Cn%20%20%20%20%20%20%20%20%20%20the%20%3Ccode%3Edeferred%3A%20!!__SERVER__%3C%2Fcode%3E%20flag.%20To%20block%20a%20route%20transition%5Cn%20%20%20%20%20%20%20%20%20%20until%20some%20data%20is%20loaded%2C%20remove%20the%20%3Ccode%3Edeferred%3A!!__SERVER__%3C%2Fcode%3E%20flag.%5Cn%20%20%20%20%20%20%20%20%20%20To%20always%20render%20before%20loading%20data%2C%20even%20on%20the%20server%2C%20use%20%3Ccode%3EcomponentDidMount%3C%2Fcode%3E.%5Cn%20%20%20%20%20%20%20%20%3C%2Fp%3E%5Cn%20%20%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20%20%20This%20widgets%20are%20stored%20in%20your%20session%2C%20so%20feel%20free%20to%20edit%20it%20and%20refresh.%5Cn%20%20%20%20%20%20%20%20%3C%2Fp%3E%5Cn%20%20%20%20%20%20%20%20%7Berror%20%26%26%20%3Cdiv%20className%3D%5C%22alert%20alert-danger%5C%22%20role%3D%5C%22alert%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3Cspan%20className%3D%5C%22glyphicon%20glyphicon-exclamation-sign%5C%22%20aria-hidden%3D%5C%22true%5C%22%3E%3C%2Fspan%3E%7B'%20'%7D%7Berror%7D%5Cn%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%7D%5Cn%20%20%20%20%20%20%20%20%7Bwidgets%20%26%26%20widgets.length%20%26%26%20%3Ctable%20className%3D%5C%22table%20table-striped%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3Cthead%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%20className%3D%7Bstyles.idCol%7D%3EID%3C%2Fth%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%20className%3D%7Bstyles.colorCol%7D%3EColor%3C%2Fth%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%20className%3D%7Bstyles.sprocketsCol%7D%3ESprockets%3C%2Fth%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%20className%3D%7Bstyles.ownerCol%7D%3EOwner%3C%2Fth%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cth%20className%3D%7Bstyles.buttonCol%7D%3E%3C%2Fth%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2Fthead%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3Ctbody%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F*%20eslint-disable%20react%2Fjsx-indent%20*%2F%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20widgets.map(widget%20%3D%3E%20(editing%5Bwidget.id%5D%20%3F%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CWidgetForm%20form%3D%7BString(widget.id)%7D%20key%3D%7BString(widget.id)%7D%20initialValues%3D%7Bwidget%7D%20%2F%3E%20%3A%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%20key%3D%7Bwidget.id%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20className%3D%7Bstyles.idCol%7D%3E%7Bwidget.id%7D%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20className%3D%7Bstyles.colorCol%7D%3E%7Bwidget.color%7D%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20className%3D%7Bstyles.sprocketsCol%7D%3E%7Bwidget.sprocketCount%7D%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20className%3D%7Bstyles.ownerCol%7D%3E%7Bwidget.owner%7D%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20className%3D%7Bstyles.buttonCol%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Cbutton%20className%3D%5C%22btn%20btn-primary%5C%22%20onClick%3D%7BhandleEdit(widget)%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ci%20className%3D%5C%22fa%20fa-pencil%5C%22%20%2F%3E%20Edit%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Fbutton%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftd%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F*%20eslint-enable%20react%2Fjsx-indent%20*%2F%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2Ftbody%3E%5Cn%20%20%20%20%20%20%20%20%3C%2Ftable%3E%7D%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) is my example in real life for the problem with the max-len, the code is not cut and there are no lines too long but prettier makes these lines too long in all cases.

**Comment by bertho-zero** [comment]
A more minimalist example [here](https://prettier.io/playground/#%7B%22content%22%3A%22import%20React%2C%20%7B%20Component%20%7D%20from%20'react'%3B%5Cn%5Cnexport%20default%20class%20Widgets%20extends%20Component%20%7B%5Cn%5Cn%20%20render()%20%7B%5Cn%20%20%20%20%5Cn%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%3Cdiv%20%2F*%20...%20*%2F%3E%5Cn%20%20%20%20%20%20%20%20%7B%2F*%20...%20*%2F%7D%5Cn%20%20%20%20%20%20%20%20%3Cp%3E%5Cn%20%20%20%20%20%20%20%20%20%20If%20you%20hit%20refresh%20on%20your%20browser%2C%20the%20data%20loading%20will%20take%20place%20on%20the%20server%20before%20the%20page%20is%5Cn%20%20%20%20%20%20%20%20%20%20returned.%20If%20you%20navigated%20here%20from%20another%20page%2C%20the%20data%20was%20fetched%20from%20the%20client%20after%5Cn%20%20%20%20%20%20%20%20%20%20the%20route%20transition.%20This%20uses%20the%20decorator%20method%20%3Ccode%3E%40asyncConnect%3C%2Fcode%3E%20with%5Cn%20%20%20%20%20%20%20%20%20%20the%20%3Ccode%3Edeferred%3A%20!!__SERVER__%3C%2Fcode%3E%20flag.%20To%20block%20a%20route%20transition%5Cn%20%20%20%20%20%20%20%20%20%20until%20some%20data%20is%20loaded%2C%20remove%20the%20%3Ccode%3Edeferred%3A!!__SERVER__%3C%2Fcode%3E%20flag.%5Cn%20%20%20%20%20%20%20%20%20%20To%20always%20render%20before%20loading%20data%2C%20even%20on%20the%20server%2C%20use%20%3Ccode%3EcomponentDidMount%3C%2Fcode%3E.%5Cn%20%20%20%20%20%20%20%20%3C%2Fp%3E%5Cn%20%20%20%20%20%20%20%20%7B%2F*%20...%20*%2F%7D%5Cn%20%20%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20%20%20)%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by kentcdodds** [comment]
Gotcha. That actually looks like a bug with prettier. Could you file it there?

**Comment by kentcdodds** [comment]
You should probably also know about [this issue](https://github.com/prettier/prettier-eslint/issues/66)

My recommendation is you disable the `max-len` rule in eslint and just rely on prettier to make everything a reasonable length for you.
