### ISSUE TITLE
Using prettier.formatWithCursor for editor integration

### ISSUE THREAD

**Issue by darahak** [prettier/prettier-eslint#115]
For https://github.com/prettier/prettier-atom/issues/34, we would like to use the new `prettier.formatWithCursor` function.

The thing is, `prettier.formatWithCursor` returns a `{ formatted: String, cursorOffset: Number }`.
`prettier-eslint` exports a single function that returns a string, so I'm not sure how to integrate it without breaking anything.

How would you do it?

**Comment by kentcdodds** [comment]
Wow! That's a _very_ cool feature!! Unfortunately I don't think that eslint provides anything to allow us to do this. So I think that unless ESLint is updated to allow for an API like this we wont be able to expose this kind of API :(

**Comment by darahak** [comment]
My bad, I focused on the Prettier part and totally forgot ESLint doesn't have that kind of API :man_facepalming:
