### ISSUE TITLE
Prettier eslint output conflicting with eslint rule

### ISSUE THREAD

**Issue by donovanhiland** [prettier/prettier-eslint#116]
**Versions**:

- `prettier-eslint` version: 6.4.2
- `node` version: 8.1.4
- `npm` (or `yarn`) version: 5.3.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```javascript
{
  extends: [
    'kentcdodds',
    'kentcdodds/react',
    'kentcdodds/jest',
    'kentcdodds/prettier',
  ],
  rules: {
    'max-len': 'off',
    'max-lines': 'off',
    'func-style': 'off',
    'no-eq-null': 'off',
    eqeqeq: 'off',
    'no-nested-ternary': 'off',
    'no-console': ['error', { allow: ['error'] }],
    semi: ['error', 'never'],
    quotes: ['error', 'single'],
    'object-curly-spacing': ['error', 'always'],
    'babel/object-curly-spacing': ['error', 'always'],
    'react/jsx-filename-extension': ['error', { extensions: ['.jsx', '.js'] }],
    'react/jsx-max-props-per-line': [2, { maximum: 1 }],
  },
}
```

**What I did:**
ran `prettier-eslint` from the cli on the file

**What happened:**
Code formatted in a way that introduced eslint errors

It looks like `eslint --fix` on the original code doesn't have an issue, but makes changes on the prettier output.
Input: 
```javascript
const Icon = props => {
  return (
    <svg
      viewBox="0 0 20 20"
      {...props}
    >
      {iconPaths.map((path, index) => (
        <path
          key={index}
          d={path}
        />
      ))}
    </svg>
  )
}
```

Prettier output:
```javascript
const Icon = props => {
  return (
    <svg viewBox="0 0 20 20" {...props}>
      {iconPaths.map((path, index) => <path key={index} d={path} />)}
    </svg>
  )
}
```
with ESlint errors:
```
22:30  error  Prop `props` must be placed on a new line  react/jsx-max-props-per-line
23:57  error  Prop `d` must be placed on a new line      react/jsx-max-props-per-line
```

eslint --fix output:
```javascript
const Icon = props => {
  return (
    <svg
      viewBox="0 0 20 20"
      {...props}
    >
      {iconPaths.map((path, index) => (<path
        key={index}
        d={path}
      />))}
    </svg>
  )
}
```

**Reproduction repository:**

https://github.com/donovanhiland/formatting-issue

**Comment by kentcdodds** [comment]
Hmmm... Maybe try uninstalling and reinstalling so you get the latest version of `prettier`. There were some significant changes in 1.6.0 of prettier just an hour ago...

**Comment by donovanhiland** [comment]
Thanks! Tried uninstalling/reinstalling and looks like the same thing is happening. Is there anything I can provide that would be more useful? 😄

**Comment by kentcdodds** [comment]
So, to be clear, the `prettier` step gives code that passes ESLint, and the `eslint --fix` step gives code that does not pass ESLint?

**Comment by donovanhiland** [comment]
`prettier` output throws ESlint error from `react/jsx-max-props-per-line`. `eslint --fix` tries to fix it, but in doing so it creates another error.

**Comment by kentcdodds** [comment]
Ah, I highly recommend disabling that rule. I used to enable it but decided against it because the whole reason I had that rule was to avoid my lines getting too long, but now that I have prettier I don't worry about that anymore.

If you come up with anything to fix this then feel free, but I wont be working on it personally ([no time](http://kcd.im/no-time)). Sorry, and good luck!
