### ISSUE TITLE
Support settings

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier-eslint#118]
Moving this from https://github.com/prettier/prettier-atom/issues/242

So here's a proposal. I think that this would actually be a change in prettier-eslint rather than prettier-atom... We could add a property in the `settings` of your eslint config to do this. For example:

```javascript
{
  "extends": "airbnb",
  "settings": {
    "prettier-eslint": {
      "rules": { "semi": [2, "never"] }
    }
  },
}
```

The `prettier-eslint` property would effectively be an eslint config that would override the rest of your config. I'm not sure how easy that would be (like supporting `extends` and stuff like that). But at _least_ having rules configured there would be really handy.

Thoughts?

I think I'm going to do this today because I just upgraded to eslint@4 and I don't like the way the indentation with JSX works with `eslint --fix`. I just want to keep the format that prettier outputs.

**Comment by zimme** [comment]
>In order to get both, you could allow passing an option for prettier-eslint that lets you override eslint rules at the time of invocation? That way you could have debuggers disabled in your eslint config, but prettier-atom could call prettier-eslint and override that rule as we assume it's okay for development? Then when you run prettier-eslint as part of a validate script or whatever, it still removes it for you.

Just wanted to bring in part of robwise's comment from the related atom-prettier issue.

**Comment by zimme** [comment]
> I don't like the way the indentation with JSX works with eslint --fix

Can't you just use `eslint-config-prettier` which disables all eslint rules that conflicts with prettier?

**Comment by kentcdodds** [comment]
I don't need this anymore and it doesn't appear that anyone plans to work on this either...

**Comment by assaftenen** [comment]
could be a real helper
