### ISSUE TITLE
Class properties quit working in 6.4.3

### ISSUE THREAD

**Issue by kobenauf** [prettier/prettier-eslint#122]
**Versions**:

- `prettier-eslint` version: 6.4.3
- `node` version: 8.4.0
- `npm` (or `yarn`) version: yarn 0.27.5

**Relevant code or config**

```javascript
class MyThing {
  someClassProp = '123'
}
```

**What I did:**
Upgraded from prettier-eslint 6.4.2 to 6.4.3.

**What happened:**

All class properties started triggering the `no-undef` eslint rule.  Prior to this upgrade they worked.

> [eslint] 'someClassProp' is not defined. (no-undef)
> (property) MyThing.someClassProp: string

**Comment by zimme** [comment]
I'm thinking this is an eslint error, that update only updated dependencies, eslint 3 to eslint 4, amd prettier 1.5 to 1.6

**Comment by zimme** [comment]
I'm closing this as it's been inactive since September. @ping me if this is still an issue.
