### ISSUE TITLE
no-semi option would add semicolons at the beginning of jsx tag name.

### ISSUE THREAD

**Issue by chemzqm** [prettier/prettier-eslint#134]
**Versions**:

- `prettier-eslint` version: 4.4.0
- `node` version: v8.5.0
- `npm` (or `yarn`) version: 5.3.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```javascript
          do {
            if (feeds.length) {
              <Feeds />
            }
          }
```

**What I did:**

Use command `prettier-eslint \"components/**/*.js\" --write --jsx-bracket-same-line --no-semi --single-quote` to format above code.

**What happened:**

```javascript
          do {
            if (feeds.length) {
              ;<Feeds />
            }
          }
```

**Suggested solution:**

The semicolons should not be added.

**Comment by azz** [comment]
This is intentional. See https://github.com/prettier/prettier/issues/1433 for rationale.

**Comment by chemzqm** [comment]
Thanks, it looks stupid, but I'm ok with that now.
