### ISSUE TITLE
Use getSupportInfo from prettier

### ISSUE THREAD

**Issue by zimme** [prettier/prettier-eslint#137]
Let's use `getSupportInfo` from prettier to make our logic simpler.

https://github.com/prettier/prettier/pull/3033

**Comment by zimme** [comment]
Do `eslint` have something similar?

**Comment by zimme** [comment]
I'm looking at a solution now that just forwards `text` to `prettier` with `filePath` if available to let prettier handle the file type detection and fall back to `babylon`. The only thing we should need to detect in this package is for which filetypes we should call `eslint`.

If this works as I'm thinking we should be able to lower the version number of `prettier` and maybe even `eslint`.

**Comment by azz** [comment]
:+1:

**Comment by zimme** [comment]
> I'm looking at a solution now that just forwards text to prettier with filePath if available to let prettier handle the file type detection and fall back to babylon. The only thing we should need to detect in this package is which filetypes we should forward to eslint.

Merged in #145.

Hmm, I'll look into lowering the version of prettier, as we don't really use any fancy api calls any more. :smile:

**Comment by zimme** [comment]
Closing this now as it's fixed with version 8.4.0 and 8.5.0.
