### ISSUE TITLE
I'm stepping down from the project.

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier-eslint#139]
Hey folks, so it's been a few months that I've not used this project anymore (I just use `prettier` now). So I will no longer be watching the repository and I'll also be removing the auto-release functionality. Someone else can set that up... on that note:

Who wants to take this project over? (I'll be doing the same for `prettier-eslint-cli`: https://github.com/prettier/prettier-eslint-cli/issues/115). 

cc everyone who's committed code to the project: @zimme, @robwise, @lukaszmoroz, @sheerun, @michaelgmcd, @edm00se, @OliverJAsh, @0x80, @enriquecaballero, @spudly, @RobinMalfait, @danielterwiel, @tommck, @aaronshaf, @pascalduez, @vlad-zhukov, @ppvg, @vine77, @markpalfreeman, @eqyiel, @mvolkmann, @Gandem, @Belir, @echenley, @ritz078, @briandipalma, @loklaan, @PAkerstrand, @lydell

**Comment by kentcdodds** [comment]
If you want to maintain the project and have publish rights, give me your npm and github usernames and I'll hand it over to you. I'm afraid I [wont have time](http://kcd.im/no-time) to contribute or help out with this project any further. Good luck!

**Comment by zimme** [comment]
I'll try and help out as much as possible. I'm hoping we can work close together with @azz and `prettier-tslint` to hopefully benefit from each other. My npm and GitHub usernames are the same `zimme`.

**Comment by kentcdodds** [comment]
Awesome @zimme, I was hoping you'd say that! :tada:

**Comment by kentcdodds** [comment]
I'll go ahead and close these issues on both repos and let you decide who you'd like to give publish rights/commit rights to now :+1:

**Comment by zimme** [comment]
I don't know how much time I will have to put into this project, but as I am using it in a few projects I'd at least like to be able to fix bugs. I will happily split the responsibility with whom ever is interested in keeping the project maintained.

**Comment by zimme** [comment]
@kentcdodds, Do you have any links to setting up the auto-release you had in place?

**Comment by kentcdodds** [comment]
Yep! http://kcd.im/write-oss

You might also just try upgrading this project to use [`kcd-scripts`](https://github.com/kentcdodds/kcd-scripts), though it's not well documented...

Good luck!

**Comment by jmenglis** [comment]
@zimme I can help out where I can.

**Comment by kentcdodds** [comment]
Actually, I didn't actually remove any of the code/config that does the auto-release stuff. I just removed the `GH_TOKEN` and `NPM_TOKEN` environment variables from the travis settings. So if you want you could just update those to be your tokens and it should "just work" :+1:

**Comment by zimme** [comment]
I'll set a side a few hours this weekend for the project, I should be able to make sure you have all the access/info you need then @jmenglis.

**Comment by eqyiel** [comment]
Thanks for your time and work on this until now @kentcdodds!

**Comment by michaelgmcd** [comment]
Thanks for the great work on this project @kentcdodds 👍
