### ISSUE TITLE
Why babel-core is in dependencies?

### ISSUE THREAD

**Issue by octref** [prettier/prettier-eslint#146]
While upgrading from V6 to V8, I noticed yarn added a lot of deps because now you include babel-core as a deps instead of devDeps.

https://github.com/prettier/prettier-eslint/commit/d04c0a15f3d7a5b345135698268926300a4b9ea4

Any reason you have to do that, or can you move babel-core to devDeps?

@zimme

**Comment by zimme** [comment]
I was getting some errors with some of the updates. I'll have a look and see if there's another way around this.
