### ISSUE TITLE
Latest release unable run with older versions of node

### ISSUE THREAD

**Issue by natelaws** [prettier/prettier-eslint#154]
**Versions**:

- `prettier-eslint` version: 8.6.0
- `node` version: 6.11.3
- `npm` (or `yarn`) version: 3.10.10

**What happened:**

With version 8.6.0 an Object.entries() call was added which does not exist in older version of node.

**Suggested solution:**

Probably the same thing as https://github.com/prettier/prettier-eslint-cli/issues/122

**Comment by zimme** [comment]
I thought `babel-preset-env` would have picked this up, but turns out it didn't.

Anyways, fix should be published with `8.6.1`

**Comment by zimme** [comment]
Version `8.6.2` should fix this properly, forgot to add `babel-runtime` to the dependencies.
