### ISSUE TITLE
String concatenation not auto converted to template with eslint integration

### ISSUE THREAD

**Issue by James2516** [prettier/prettier-eslint#155]
**Versions**:

- `prettier-eslint` version: 8.3.1
- `node` version: 8.6.0
- `npm` (or `yarn`) version: yarn 1.3.2
 
**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes
**Relevant code or config**

```
{
  "root": true,
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "env": {
      "es6": true
  },
  "parser": "babel-eslint",
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "react/prop-types": 0,
    "no-console": 0,
    "arrow-parens": ["error", "always"],
    "prefer-template": "error"
  }
}
```

.prettierrc:
```
{
  "singleQuote": true,
  "trailingComma": "all",
  "arrowParens": "true"
}
```

**What I did:**

![](https://i.imgur.com/l0vxjBI.png)

**What happened:**

I have eslint integration enabled, eslint's autofix should automatically convert the above to \`${x}b\` but this did not happen.

**Reproduction repository:**

**Problem description:**

**Suggested solution:**

**Comment by zimme** [comment]
Pretty sure this is solved in 8.7.6.
