### ISSUE TITLE
Recently on some javascript files, prettier started to break the whole code

### ISSUE THREAD

**Issue by THPubs** [prettier/prettier-eslint#159]
Recently, me and my team started to get errors with prettier in vscode. Most of the time it works but sometimes for some files it breaks. Here's an example code before running prettier:

![screenshot from 2018-01-16 13 20 19](https://user-images.githubusercontent.com/1212023/34977641-550aa4ce-fac1-11e7-946b-690114b51c57.png)

And here's after using prettier:

![screenshot from 2018-01-16 13 20 30](https://user-images.githubusercontent.com/1212023/34979609-ce1c6fae-fac7-11e7-83fd-591440165f9b.png)

We are using prettier with eslint:

    "devDependencies": {
      "babel-plugin-import": "^1.6.2",
      "cross-env": "^5.1.3",
      "eslint": "^3.19.0 || ^4.3.0",
      "eslint-config-airbnb": "^15.1.0",
      "eslint-plugin-import": "^2.7.0",
      "eslint-plugin-jsx-a11y": "^5.1.1",
      "eslint-plugin-react": "^7.1.0",
      "husky": "^0.14.3",
      "nsp": "^3.1.0",
      "prettier-eslint": "^8.2.0",
      "react-app-rewire-less": "^2.1.0",
      "react-app-rewired": "^1.3.5"
    },

Any idea why it's happening?

**Comment by zimme** [comment]
Could you please verify that it's not `prettier` or `eslint` that's breaking the code by running them separately. without `prettier-eslint`.

**Comment by drumnation** [comment]
This just started happening to me too today.  I'm still trying to figure out what might be the cause of it as I didn't change anything in my configuration.

**Comment by THPubs** [comment]
@zimme Just did some investigation and looks like it's caused by prettier. Disabled prettier-eslint integration. It still messed up. Next tried eslint auto fix only. It worked fine. So looks like it's prettier. Any idea why?

**Comment by azz** [comment]
Since you turned off `prettier-eslint` and the problem persisted we should close this issue and use the duplicate https://github.com/prettier/prettier-vscode/issues/330 to track down the issue.

**Comment by THPubs** [comment]
@azz Agreed!
