### ISSUE TITLE
Support `eslintrcPath`

### ISSUE THREAD

**Issue by davidosomething** [prettier/prettier-eslint#16]
For some projects there is a custom path to eslintrc files, hence support for `  -c, --config path::String    Use configuration from this file or shareable config` in the eslint cli http://eslint.org/docs/user-guide/command-line-interface

Can you add support for `--eslintrcPath` to mirror that functionality (eslintConfig takes an object instead of path)

This should also be passed through to `prettier-eslint-cli`

**Comment by kentcdodds** [comment]
Happy to support that. Would you be willing to [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by davidosomething** [comment]
sure i'll give it a go

**Comment by zimme** [comment]
This is already supported, https://github.com/prettier/prettier-eslint-cli#cli-options. Please ping me if this needs to be reopened.
