### ISSUE TITLE
Add support for Prettier.formatWithCursor

### ISSUE THREAD

**Issue by SavePointSam** [prettier/prettier-eslint#164]
prettier-atom will soon have support for [prettier.formatWithCursor](https://prettier.io/docs/en/api.html#prettierformatwithcursorsource-options). However, in certain situation's it has a fallback to this package. In order to support cursor retention in all cases, this package needs to add support for it as well.

**Comment by zimme** [comment]
I've had a quick look at eslint's api and I can't find any support for providing and getting cursor information, which would make this impossible for all cases when eslint is used.

I'm pretty swamped at work so I would appreciate any help I can get here.

Worst case, we should be able to provide `formatWithCursor` that only runs prettier, until such time that eslint supports this too.

As I said, I've just had a quick look at the api and can't find support for this, but please have a closer look as I might have missed it.
