### ISSUE TITLE
TypeScript adding 36mb to install size

### ISSUE THREAD

**Issue by mikestead** [prettier/prettier-eslint#166]
We've been evaluating our `node_modules` as they've grown large recently and are causing slowdowns in CI execution times, even after caching.

At the top of the list is `prettier-eslint@8.8.1`  at `~37mb`. The main culprit of this appears to be the direct `TypeScript` dependency at `36mb`.

![screen shot 2018-03-05 at 9 59 39 am](https://user-images.githubusercontent.com/56844/36951810-f5ec257e-205b-11e8-847c-b29e4df655cd.png)

We don't use `TypeScript` currently so this is a lot of baggage to download for something not in use.

We're wondering if it's possible to make this a `peerDependency`? Or even if `TypeScript` support should be housed under a different lib?

I know this would be seen as a breaking change but putting it out there as does have a significant impact.

Thanks for the work on this project.

**Comment by zimme** [comment]
Even if I were to add typescript as a peerDependency it wouldn't help as prettier itself has typescript as a dependency because of the exact same reason this package, to be able to use typescript-eslint-parser to parse typescript files.

**Comment by mikestead** [comment]
Interesting, when I `npm install` `Prettier` it doesn't seem to bring in any dependencies (although it is 9.9mb). I guess when they publish they do some [bundling](https://github.com/prettier/prettier/blob/master/scripts/build/build.js#L95)?

**Comment by zimme** [comment]
Yeap, they seem to use rollup. We should be able to do that too, but I currently don't have time to look at that.

So for your CI case, can't you cache node_modules?

**Comment by mikestead** [comment]
@zimme no worries at all.

We do indeed use caching in bitbucket pipelines, unfortunately it still takes a bit of time to download the zip'd cache each run!

**Comment by DanielFGray** [comment]
Is there no way to make it a peerDependency or devDependency?
