### ISSUE TITLE
How to provide eslintIntegration option to .prettierrc 

### ISSUE THREAD

**Issue by therise3107** [prettier/prettier-eslint#167]
Hey, First of all, I am not sure if this is an issue. What I am trying to do is to separate the `prettier.eslintIntegration`
from `VsCode` and `Atom` into `.prettierrc.js` file. 

I have enabled `eslint` and using `.eslintrc.js` for that now I want to pass this file to `prettier-eslint` via `.prettierrc.js`. 

I have tried providing `eslintConfig: { filePath: './.eslintrc.js' },  eslintPath: './.eslintrc.js',` but It seams prettier-eslint  is not loading config from eslint in my case.

Any help would be highly Appreciated.
Thank you in advance.

node: 8.9.4
prettier-eslint: ^8.8.1
yarn: 1.5.1

**Comment by zimme** [comment]
Sorry but the prettier-eslint integration option is an option specific for prettier-vscode and prettier-atom and can't be specified in the prettier config file.

**Comment by therise3107** [comment]
Thank you @zimme closing this.
