### ISSUE TITLE
Bump Prettier to latest version

### ISSUE THREAD

**Issue by Yohanna** [prettier/prettier-eslint#169]
**Versions**:

- `prettier-eslint` version: 8.8.1
- `node` version: 8.11.1
- `npm` version: 5.8.0
- `yarn` version: 1.5.1

**Problem description:**

`prettier-eslint` currently uses v`1.7.0` of `prettier`. However latest `prettier` is at v`1.12.0`, it'd be great to upgrade to the latest version!

I can work on a PR to upgrade the version if that's ok?

**Comment by zimme** [comment]
prettier is defined as a version range ^1.7.0 which will accept newer versions of prettier.

**Comment by Yohanna** [comment]
That's what I thought, but when I look under `node_modules` I see prettier v`1.10.2` (using npm). If I used yarn, I get v`1.11.0`, I never get the latest version, v`1.12.0` 😕
