### ISSUE TITLE
Add support for the --ignore-path CLI option

### ISSUE THREAD

**Issue by kripod** [prettier/prettier-eslint#170]
Currently, when I try to use Prettier's [`--ignore-path`](https://prettier.io/docs/en/cli.html#ignore-path) CLI option with prettier-eslint, I come across many of the following error messages:

```
Ignored unknown option `{ "ignorePath": "./.gitignore" }`.
```

**Comment by azz** [comment]
`--ignore-path` is a CLI flag and does not work in config files.

**Comment by kripod** [comment]
Sure, but it’d be great if prettier-eslint could support the `--ignore-path` CLI flag.

**Comment by azz** [comment]
Sounds like an enhancement for https://github.com/prettier/prettier-eslint-cli?

**Comment by kripod** [comment]
Yeah, definitely, I’ll move this issue over there. Thanks for informing me!

**Comment by kripod** [comment]
I have just moved this issue to https://github.com/prettier/prettier-eslint/issues/170
