### ISSUE TITLE
No CLI

### ISSUE THREAD

**Issue by domoritz** [prettier/prettier-eslint#171]
**Versions**:

- `prettier-eslint` version: ??
- `node` version: 9
- `yarn` version: 1.6.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**What I did:**

Install prettier eslint. `yarn add prettier-eslint --dev`

**What happened:**

```
$ yarn run prettier-eslint
yarn run v1.6.0
error Command "prettier-eslint" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ ls node_modules/.bin/              
acorn
eslint
esparse
esvalidate
js-yaml
mkdirp
prettier
rimraf
semver
tsc
tsserver
which
```

**Comment by zimme** [comment]
```
yarn add prettier-eslint-cli
```

**Comment by domoritz** [comment]
Thanks @zimme! I got confused when I saw a bunch of mentions in the issues.
