### ISSUE TITLE
Prettier does not respect the "no-multiple-empty-lines" rule of eslint

### ISSUE THREAD

**Issue by m-diiorio** [prettier/prettier-eslint#176]
Prettier removes any multiple empty lines collapsing to max 1 empty line.
I understand the default behavior but I would like to override it with eslint

**Example with my rule (google/airbnb style guide):**
`"no-multiple-empty-lines": ["error", { "max": 2 }]`

```js
a = 1


b = 2
```
Becomes:
```js
a = 1

b = 2
```
----
Opinionated behavior should only be the default and should be configurable.
Ref: https://github.com/prettier/prettier/issues/1613

**Comment by zimme** [comment]
This is not possible as the output eslint gets is already ran though prettier. The only way to get the outcome you're after is to add an option about this in prettier.

**Comment by manuel-di-iorio** [comment]
Yes I'm looking for an option in Prettier for this, but cannot see any here: https://prettier.io/docs/en/options.html.
I will create an Issue in their repo, thanks

**Comment by zimme** [comment]
I'm thinking that for your case if you really don't want the prettier way of formatting then maybe it's just better for you to go with using eslint only.

**Comment by manuel-di-iorio** [comment]
@zimme Thank you zimme, I'm evaluating also that, but if I'm not in wrong, Prettier can format better than eslint in some cases, that's why I was using it in the first place. 
Will think about, thanks 👍

**Comment by robmoggach** [comment]
Prettier rocks... I want two spaces between my functions and classes... please!!!

**Comment by zimme** [comment]
We can't do anything about this until prettier changes its formatting or add an option to allow multiple empty lines.

I'm closing this and you can open a new issue for this feature once prettier allow for this type of formatting.

Eslint isn't powerful enough to revert  all formatting that prettier imposes.

**Comment by Tester798** [comment]
Yeah, sometimes I like to add two empty lines for better code readability, but prettier is leaving only one line there after formatting. Would be nice to have configurable option for this.

**Comment by helight59** [comment]
Why do they decide for us what will be more beautiful for our project?

**Comment by MWatzlaw** [comment]
Yes, I make my code much mor readable using multiple empty lines! Why ignoring such an important thing, so much user asking for?
Hey, if they hate it, nobody is pushed to do that. But why the user fortbidding to do so?

**Comment by JounQin** [comment]
Complain helps nothing.
