### ISSUE TITLE
replace `↹` with `··` prettier/prettier

### ISSUE THREAD

**Issue by qingfengmy** [prettier/prettier-eslint#177]
![image](https://user-images.githubusercontent.com/4978379/40154453-f80f162e-59c0-11e8-8dba-f76d423c329d.png)

How to deal with this error ？？

**Comment by zimme** [comment]
I'm pretty sure this error message is that on line 4 in that file you have a tab character instead if 2 spaces which is something prettier expect. Also this error seems to be coming from `eslint-plugin-prettier` as it's a linting error. This package automatically formats those errors instead.
