### ISSUE TITLE
Line Length Issues - All the time

### ISSUE THREAD

**Issue by bradennapier** [prettier/prettier-eslint#182]
**Versions**:

- `prettier-eslint` version: 8.8.2 
- `node` version: 10.6.0
- `npm` (or `yarn`) version: 1.7.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```javascript
function getHashDiffPromiseOf(type, model, nextHashData, blockNumber, transaction) {
  return Promise.all(
    Object.keys(nextHashData).map(value => applyHashDiffFor(
      model,
      { [type]: value },
      nextHashData[value],
      blockNumber,
      transaction,
    )),
  );
}
```

**What I did:**

Ran prettier-eslint

**What happened:**

It took a line that conforms to the eslint spec and breaks it:

```javascript
function getHashDiffPromiseOf(type, model, nextHashData, blockNumber, transaction) {
  return Promise.all(
    Object.keys(nextHashData).map(value => applyHashDiffFor(model, { [type]: value }, nextHashData[value], blockNumber, transaction)),
  );
}
```

I often find myself having to try to force prettier in these case but sometimes this isn't really possible.

```javascript
function getHashDiffPromiseOf(type, model, nextHashData, blockNumber, transaction) {
  return Promise.all(
    Object.keys(nextHashData).map(value => applyHashDiffFor(
      // $ prettier dont break me! $ //
      model,
      { [type]: value },
      nextHashData[value],
      blockNumber,
      transaction,
    )),
  );
}
```

I strictly enforce 0 eslint errors on almost all of our projects so this is a constant problem for us :(.  Hoping its a straight forward fix!

**Reproduction repository:**

Not really needed, this type of things happens alll the time - I always find situations where its breaking this rule in some major way - often when it could easily get around it as well (like object call chains, etc).

```javascript
"max-len": [
      "error",
      {
        "code": 100,
        "ignoreComments": true,
        "ignoreStrings": true,
        "ignoreTemplateLiterals": true
      }
    ]
```

that is the max-len config i currently have.

**Suggested solution:**

When it is going to be a change that breaks eslint rules, it should not make any change

**Comment by bradennapier** [comment]
still having this issue...

**Comment by j-f1** [comment]
You can either resolve this by increasing the `printWidth` in your Prettier config, or by adding a `// prettier-ignore` line like so:

```js
function getHashDiffPromiseOf(type, model, nextHashData, blockNumber, transaction) {
  return Promise.all(
    // prettier-ignore
    Object.keys(nextHashData).map(value => applyHashDiffFor(model, { [type]: value }, nextHashData[value], blockNumber, transaction)),
  );
}
```

**Comment by marek-sed** [comment]
@bradennapier I am having the same issue, but found a strange behaviour were { code: 99 } is working properly but { code: 100 } is not.

is it doing the same thing in your config?

**Comment by jabacchetta** [comment]
I've got both `max-len` and `printWidth` set at 100. Yet, my lines seem to be formatting with no limit at all?

**Comment by marek-sed** [comment]
I figured it out, in my case there was a conflict in rules. We are extending abnb-guide.

Setting the  'function-paren-newline': 'off' did the trick and allowed the prettier to format properly.

**Comment by jabacchetta** [comment]
@marek-sed Mind posting your entire config? I'm extending airbnb as well. I tried adding `"function-paren-newline": "off"` with no luck. `prettier-eslint` is still formatting with no `printWidth`/`max-len` limit at all.

**Comment by jabacchetta** [comment]
What did end up working for me is adding `"implicit-arrow-linebreak": "off". Unfortunately this isn't the formatting I'm looking for. I suppose this might be a separate issue that needs to be opened.

**Comment by marek-sed** [comment]
@jabacchetta nice find, I turned it off, it seems there are few rules that can conflict with line formatting.
