### ISSUE TITLE
Trailing comma

### ISSUE THREAD

**Issue by kserjey** [prettier/prettier-eslint#184]
**Versions**:

- `prettier-eslint` version: 8.8.2
- `node` version: 10.6.0
- `npm` (or `yarn`) version: 6.2.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

No

**Relevant code or config**

_ESLint Config_

```json
{
  "parser": "babel-eslint",
  "extends": ["airbnb", "prettier", "prettier/react"],
  "env": {
    "jest": true
  },
  "rules": {
    "radix": ["error", "as-needed"],
    "arrow-parens": ["error", "as-needed", { "requireForBlockBody": true }],
    "jsx-quotes": ["error", "prefer-single"],
    "react/jsx-filename-extension": ["error", { "extensions": [".js"] }],
    "react/jsx-tag-spacing": ["error", { "beforeSelfClosing": "never" }],
    "react/require-default-props": "off",
    "import/prefer-default-export": "off",
    "import/no-extraneous-dependencies": "off"
  }
}
```
_Prettier Config_

```json
{
  "singleQuote": true,
  "trailingComma": "es5"
}
```

_Test case_

```javascript
const format = require('prettier-eslint');

const text = `
const defaultOptions = {
  mapPropsToValue: () => undefined,
  mapPropsToRequest: () => null,
  shouldDataUpdate: () => false,
};
`;

const formatted = format({ text });
```

**Problem description:**

Expected output is:

```javascript
const defaultOptions = {
  mapPropsToValue: () => undefined,
  mapPropsToRequest: () => null,
  shouldDataUpdate: () => false,
}
```

But actual result is :woman_shrugging: 

```javascript
const defaultOptions = {
  mapPropsToValue: () => undefined,
  mapPropsToRequest: () => null,
  shouldDataUpdate: () => false
}
```

We've lost a trailing comma!

**Suggested solution:**

I think that the problem is here:

https://github.com/prettier/prettier-eslint/blob/f33b95333a64ea85f2b7c77bdc24013e9599996c/src/utils.js#L206-L223

Because if `eslintValue` is `RULE_DISABLED` it passes `typeof eslintValue === 'object'` and `getValFromTrailingCommaConfig` accepts wrong value.

**Comment by sziraqui** [comment]
This is still an issue. OP has stated everything correctly. Was this fixed?
