### ISSUE TITLE
how to treat `.babelrc` as normal json file?

### ISSUE THREAD

**Issue by fatfatson** [prettier/prettier-eslint#185]
now it always format the `.babelrc` as js file, then vscode give lots of problems:
![image](https://user-images.githubusercontent.com/5842874/43831674-79152bf2-9b37-11e8-9545-37a31a34bde6.png)

**Comment by biw** [comment]
You can use a `babel.config.js` file and vscode shouldn't give you issues 😄 
https://babeljs.io/docs/en/next/configuration.html#babelconfigjs

**Comment by zimme** [comment]
If you don't provide a parser to prettier it defaults to using the `babel` parser when the file type is unknown. So unless we want to start checking for file types stuff in our code, which I'm not so keen on, this will be solved in the next major version of prettier as that won't default to a parser for unknown files.
