### ISSUE TITLE
No auto line break in long arrow functions

### ISSUE THREAD

**Issue by James2516** [prettier/prettier-eslint#190]
**Versions**:

- `prettier-eslint` version: 8.8.1
- `node` version: 8.12.0
- `npm` (or `yarn`) version: 1.6.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```
{
  "root": true,
  "extends": "airbnb"
}
```

**What I did:**

Declare a long arrow function:
```
const longArrowFunction = size => [...Array(size)].map(() => [...Array(size)].map(() => [...Array(size)]));
```

**What happened:**

Line exceeded max line length warning is given.

I tried to move it to a new line:
```
const longArrowFunction = size => 
  [...Array(size)].map(() => [...Array(size)].map(() => [...Array(size)]));
```
But it autoformatted to single line due to `implicit-arrow-linebreak` warning.

How should I resolve this without adding a rule to ignore line max length warning?

**Comment by Zemelia** [comment]
True, have same issue.

**Comment by yyjazsf** [comment]
use rule implicit-arrow-linebreak ?

**Comment by jabacchetta** [comment]
This can be solved by using `"implicit-arrow-linebreak": "off",` but that would defeat the purpose (wanting to give priority to ESLint).

This might be a [limit of prettier](https://github.com/prettier/prettier/issues/2065)?

Unfortunately this makes Prettier unusable with the Airbnb style guide, unless wanting to give priority to Prettier's formatting (i.e. [using eslint-plugin-prettier along with the recommended configuration](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration)).
