### ISSUE TITLE
What if eslint cannot fix what prettier generated in the future?

### ISSUE THREAD

**Issue by yanni4night** [prettier/prettier-eslint#191]
I'm using prettier-eslint well. But I'm wondering, someday in the future,  if eslint cannot fix the result of prettier, what will be a solution?

E.g.

The code *A* is my source, and I prefer this style, but prettier forces to format at its own rule which cannot be configured, then eslint cannot fix it back to *A*, then report an error, what will we do?

I cannot find out a real example like this at the moment, but I worry about it in the future.

**Comment by zimme** [comment]
I recommend using `eslint-config-prettier` when using this package. i.e. disable all eslint rules that are conflicting with prettier. This way eslint will be a compliment to prettier and you're not pitting them against each other.

If you are using eslint --fix to undo most of what prettier does, maybe not using prettier is the better option for you?

**Comment by yanni4night** [comment]
@zimme 😂 I guess.

**Comment by zimme** [comment]
I'll close this and we can take up this discussion again if and when this becomes a problem.
