### ISSUE TITLE
Support eslint 5

### ISSUE THREAD

**Issue by jingsam** [prettier/prettier-eslint#193]
ESlint 5 have released for a period of time, would you considering add support of it?

**Versions**:

- `prettier-eslint` version:
- `node` version:
- `npm` (or `yarn`) version:

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes || No

**Relevant code or config**

```javascript

```

**What I did:**

**What happened:**

**Reproduction repository:**

**Problem description:**

**Suggested solution:**

**Comment by pastelsky** [comment]
I second the thought that `prettier-eslint` should have listed `prettier` and `eslint` as `peerDependencies`. This, especially since `prettier-eslint` does not import these dependencies anywhere in its code.

**Comment by zimme** [comment]
Will accept a pr for this

**Comment by zimme** [comment]
I'm looking into this today.
