### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by zimme** [prettier/prettier-eslint#202]
Tests are currently failing and it's keeping us from releasing any new code for this package.

The tests are failing because `prettier` updated `comsiconfig` and it's reading files a bit differently and is resulting in failing tests because of how we mock the filesystem for our tests.

We need to find a better way to mock the filesytem i.e. the `fs` module and the `require` calls.

@azz @vjeux Feel free to chime in if you have experience with testing and mocking or mentioning people with testing skillz

**Comment by zimme** [comment]
I've done some fs mocking in my `linter` packages i.e. [here](https://github.com/linterjs/provider-eslint/blob/552b0783b7d25f057ef8f7813e6f862123de44b5/src/linter.test.ts#L5-L11)

That's using some in memory fs and unionfs with the real fs but I haven't had time to test this in this project yet.

**Comment by cjones26** [comment]
Apologies if this is a poor suggestion, but couldn't we just do something like so:

```
function getPrettierConfig(filePath, prettierPath) {
  const prettier = requireModule(prettierPath, "prettier");
  let config;

  try {
    config =
      prettier.resolveConfig &&
      prettier.resolveConfig.sync &&
      prettier.resolveConfig.sync(filePath);
  } catch (error) {
    config = {};
  }

  return config;
}
```

Of course this isn't a full solution but it did get most of the tests running as we avoid failing due to the ".prettierrc.js not found" error.

**Comment by zimme** [comment]
Tests are finally fixed :tada:

I'll try and merge PR's and get a new version of the package out ASAP.
