### ISSUE TITLE
It does not finish after running it.

### ISSUE THREAD

**Issue by vomvoru** [prettier/prettier-eslint#204]
**Versions**:

- `prettier-eslint` version: 8.8.2
- `node` version: 8.9.1
- `npm` (or `yarn`) version: 6.5.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

eslintrc.js
```js
module.exports = {
  extends: ['airbnb'],
  parser: 'babel-eslint',
  "parserOptions": {
      "ecmaVersion": 2018,
      "sourceType": "module"
  },
  env: {
    browser: true,
    es6: true,
    jest: true,
  },
  rules: {
    'import/no-extraneous-dependencies': 'off',
    'import/no-unresolved': 'off',
  },
};
```

index.js
```js
import typescript from 'typescript';
// document.body.innerHTML = typescript.version;
```

**What I did:**

```shell
prettier-eslint index.js
```

**What happened:**

```shell
prettier-eslint index.js
```
and.. My computer has stopped.

**Reproduction repository:**

https://github.com/vomvoru/prettier-eslint-issue-204

```shell
$ git clone git@github.com:vomvoru/prettier-eslint-issue-204.git
$ cd prettier-eslint-issue-204
$ npm install

# problem script
$ npm run prettier-eslint:airbnb:babel-eslint

# no problem scripts
$ npm run prettier-eslint:airbnb
$ npm run prettier-eslint
$ npm run prettier
$ npm run eslint

```

**Problem description:**

eslint airbnb template + babel-eslint + prettier-eslint + code: import ts from 'typescript';
= The CPU usage is 99%.

**Comment by chinesedfan** [comment]
Fixed by #194. Waiting for the next release.

The culprit was that settings of `import/ignore` were lost. Then the parser would try to parse the whole typescript lib, which costed very long time.
