### ISSUE TITLE
React fragments + .tsx + ESLint `quotes` rule

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-eslint#207]
**Versions**:

All latest at time of writing

- `@typescript-eslint/parser` version: 1.7.0 (latest at time of writing)
- `prettier-eslint` version: 8.8.2 (latest at time of writing)
- `node` version: 8.15.1
- `npm` (or `yarn`) version: 1.13.0
- `eslint` version: 5.16.0 (latest at time of writing)

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

`main.tsx`:

```tsx
<>foo</>;
```

`.eslintrc.js`:

```js
module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      // Workaround: disabling this fixes the problem
      jsx: true
    }
  },
  rules: {
    quotes: [2]
  }
};
```

**What I did:**

``` sh-session
$ prettier-eslint main.tsx
<>"o"</>;
success formatting 1 file with prettier-eslint
```

**What happened:**

**Reproduction repository:**

https://github.com/OliverJAsh/prettier-eslint-react-fragment

Checkout and run `yarn`.

**Problem description:**

The output is corrupt.

**Suggested solution:**

**Comment by OliverJAsh** [comment]
There are a combination of different tools being used here, but I filed the issue with prettier-eslint since the issue doesn't occur when running `prettier` nor `eslint --fix`.

**Comment by OliverJAsh** [comment]
Aha, the issue seems to stem from the fact that prettier-eslint is _overriding_ the `parser` option (defined in `.eslintrc.js`) to `typescript-eslint-parser` (an old version). Only when using this old version of the TS ESLint parser, the issue I demonstrated occurs.

This is what the call from prettier-eslint to ESLint looks like:

``` js
const eslint = require("eslint");
const cliEngine = new eslint.CLIEngine({
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    }
  },
  rules: {
    quotes: [2]
  },
  // `parser` option is overrided to use old version (!)
  parser: "typescript-eslint-parser",
  fix: true
});

console.log(
  cliEngine.executeOnText("<>foo</>", "main.tsx", true).results[0].output
);
// <>"o"</>
```

I believe that prettier-eslint should not override `parser` if one has already been defined. That would avoid this issue from occurring.

`typescript-eslint-parser` is an old version. Here we are trying to use the newer `@typescript-eslint/parser`. Here's proof that the issue doesn't occur when using the newer parser:

``` js
const eslint = require("eslint");
const cliEngine = new eslint.CLIEngine({
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    }
  },
  rules: {
    quotes: [2]
  },
  parser: "@typescript-eslint/parser",
  fix: true
});

console.log(
  cliEngine.executeOnText("<>foo</>", "main.tsx", true).results[0].output
);
```

**Comment by zimme** [comment]
Yeah, we have some problems that needs solving but tests needs to be fixed before we can publish any new version as we need to make sure nothing breaks.

**Comment by OliverJAsh** [comment]
@zimme What do you think the correct fix is here? To allow the user to use their own TS parser (in much the same way prettier-eslint lets you use your own version of ESLint)?

To verify the fix, I tried commenting out this: https://github.com/prettier/prettier-eslint/blob/f33b95333a64ea85f2b7c77bdc24013e9599996c/src/index.js#L125-L127

When I did so, the issue no longer occurred.

**Comment by zimme** [comment]
https://github.com/prettier/prettier-eslint/issues/201
