### ISSUE TITLE
Cannot read property 'range' of null

### ISSUE THREAD

**Issue by tim0991** [prettier/prettier-eslint#213]
**Versions**:

- `prettier-eslint` version: 4.7.1
- `node` version: 10.16.0
- `npm` (or `yarn`) version: yarn 1.5.1

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**
yes 

**Relevant code or config**

.eslintrc
```javascript
module.exports = {
  extends: [
    'eslint-config-alloy/typescript',
  ],
  globals: {
    _: false
  },
  rules: {
    // 这里填入你的项目需要的个性化配置，比如：
    //
    // 一个缩进必须用两个空格替代
    'indent': [
      'error',
      2,
      {
        SwitchCase: 1,
        flatTernaryExpressions: true
      }
    ],
    // 一个缩进必须用两个空格替代
    '@typescript-eslint/indent': [
      'error',
      2,
      {
        SwitchCase: 1,
        flatTernaryExpressions: true
      }
    ]
  }
};

```
vscode setting
```json

  "eslint.validate": [
    "javascript",
    "javascriptreact",
    {
      "language": "html",
      "autoFix": true
    },
    // {
    //   "language": "vue",
    //   "autoFix": true
    // },
    {
      "language": "vue-html",
      "autoFix": true
    },
    {
      "language": "typescript",
      "autoFix": true
    }
  ],
  "eslint.options": {
    // "plugins": ["vue"],
    //   "ignorePath": ".eslintignore"
    "extensions": [".js", ".vue"]
  },
  "eslint.autoFixOnSave": false,
  "prettier.eslintIntegration": true,
  "prettier.disableLanguages": [],

```

product.ts
```typescript
/**
 * 负责产品相关的 api
 */
import fly from "@/libs/fly";
import {FlyRes, FR} from "types/expend";


// 加载产品信息
export async function fetchProducts(): Promise<FR<ProductRes[]>> {
  try {
    let res = await fly.get("/products") as FlyRes;
    return res as FR;
  } catch (e) {
    return e;
  }
}

// 返回一个具体的产品详情
export async function getProduct(id: number): Promise<FR<ProductRes>> {
  try {
    let res = await fly.get(`/products/${id}`) as FlyRes;
    return res as FR;
  } catch (e) {
    return e;
  }
}

```

**What I did:**  
format a typescript file `product.ts` in vscode cause errors
`prettier-eslint src/services/product.ts` cause errors 
`eslint src/services/product.ts` is ok

**What happened:**
![image](https://user-images.githubusercontent.com/26053904/59647073-6962dd00-91ac-11e9-84ea-c378b630f9a8.png)
![image](https://user-images.githubusercontent.com/26053904/59647480-e9d60d80-91ad-11e9-8093-8aba4bce258f.png)

![image](https://user-images.githubusercontent.com/26053904/59647531-19851580-91ae-11e9-988e-ad1845f44a96.png)
![image](https://user-images.githubusercontent.com/26053904/59647579-56e9a300-91ae-11e9-9398-b9815fc9f214.png)

**Reproduction repository:**

**Problem description:**

**Suggested solution:**

**Comment by chinesedfan** [comment]
Can you try the latest 5.0.0?

**Comment by tim0991** [comment]
prettier-eslint 5.0.0？ install globally or install locally

**Comment by chinesedfan** [comment]
> Can you try the latest 5.0.0?

Sorry, I mean `prettier-eslint-cli@5`, which includes the latest `prettier-eslint@9`.

`prettier-eslint` is one of `prettier-vscode`'s dependencies. So upgrade to `prettier-eslint@9` in `prettier-vscode` should fix your issue.

**Comment by tim0991** [comment]
you are right

1. ~/.vscode/extensions/esbenp.prettier-vscode-${version}
2. yarn add prettier-eslint@9
3. restart vscode
