### ISSUE TITLE
Wrong indentation when formatting with eslint rule brace-style as stroustrup

### ISSUE THREAD

**Issue by fab1o** [prettier/prettier-eslint#226]
**Versions**:

- `prettier-eslint` version: ^9.0.0
- `node` version: 10.16.0
- `npm` (or `yarn`) version: 6.10.1

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```javascript
function test() {
    try {
        console.log('try');
    } catch (ex) {
        console.log(ex);
    }
}
```

**.eslintrc**
```
{
    "rules": {
        "brace-style": ["error", "stroustrup"]
    }
}
```

**What I did:**

`prettier-eslint --write "*.js"`

**What happened:**

Code was formatted this way:
```js
function test() {
    try {
        console.log('try');
    }
 catch (ex) { //wrong indentation here
        console.log(ex);
    }
}
```

**Reproduction repository:**

**Problem description:**

No indentation on line 5. even if my code is properly indented and following ESLint rules properly, prettier will reformat it and screw up indentation.

**Suggested solution:**

Code should be formatted this way:

```js
function test() {
    try {
        console.log('try');
    }
    catch (ex) {
        console.log(ex);
    }
}
```

**Comment by Delvach** [comment]
I'm running into this same issue. I've been advocating the use of prettier, but my current team uses 'stroustrup' bracket style and I have to manually fix the indentation issue to pass code reviews. It would be great to have an option to control this behavior.

**Comment by academicjargon** [comment]
Same issue. True for Allman as well. Using atom-beautify because of it (which has its own, less intolerable issues... )

**Comment by zdm** [comment]
Same issue, indentation is broken.

**Comment by MrFoxPro** [comment]
any updates here?

**Comment by alexseitsinger** [comment]
It's worth mentioning that I was able to resolve this issue by enabling [@typescript-eslint/indent](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md) for TypeScript and [indent](https://eslint.org/docs/rules/indent) for plain JavaScript.
