### ISSUE TITLE
Option `--throws` doesn't appear to exist

### ISSUE THREAD

**Issue by ericbiewener** [prettier/prettier-eslint#244]
**Versions**:

- `prettier-eslint` version: 9.0.0

The documentation mentions a `--throws` option but this simply doesn't appear to exist.

**Comment by zimme** [comment]
The documentation is a bit unclear, it's not actually documenting an option, but a behaviour of prettier-eslint. If you look closer at the previous options that are documented they are appended by the type of input the flags would accept and the headlines are a size smaller.

I'll keep this issue open to track updating the docs to make this more clear.
