### ISSUE TITLE
Cannot find module '../util/ast-utils'

### ISSUE THREAD

**Issue by cutanzi1997** [prettier/prettier-eslint#256]
**Versions**:

- `prettier-eslint` version:^9.0.0
- `node` version:v10.16.0
- `npm` version:6.12.0
- `eslint` version:6.5.1

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

No

**Relevant code or config**

```json
{
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:react/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "prettier/react"
  ],
  "plugins": ["prettier", "@typescript-eslint", "react"],
  "rules": {
    "prettier/prettier": "error"
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "project": "./tsconfig.json"
  }
}


```

**What I did:**

**What happened:**

**Reproduction repository:**

**Problem description:**

Cannot find module '../util/ast-utils'

**Suggested solution:**

**Comment by cutanzi1997** [comment]
"prettier.parser": "flow",

**Comment by reduardo7** [comment]
Why it is closed? Still not working!
