### ISSUE TITLE
Any plan to have it supported by vscode?

### ISSUE THREAD

**Issue by elaijuh** [prettier/prettier-eslint#29]
That will be awesome to have it for vscode

**Comment by kentcdodds** [comment]
Someone mentioned they wanted to make a vscode plugin, but I haven't heard anything since then. How would you like to try it out?

**Comment by elaijuh** [comment]
i cannot guarantee that, will try to do it.

**Comment by kentcdodds** [comment]
Sweet! @RobinMalfait has released a version: https://github.com/RobinMalfait/prettier-eslint-code

I'm closing this issue. Feel free to continue discussion on development over there!
