### ISSUE TITLE
Support ESLint 7

### ISSUE THREAD

**Issue by chrisbobbe** [prettier/prettier-eslint#401]
Hi! 👋 

Do I assume correctly that ESLint 7 isn't supported yet? I'm looking at the fact that [`eslint`'s version range in `dependencies`](https://github.com/prettier/prettier-eslint/blob/master/package.json#L24) doesn't include 7. (If `eslint` were a peer dependency, I'd get a stronger signal; there would be a peer-dep warning at install time if I didn't depend directly on a valid version of `eslint`.)

If so, here's an issue for it! 🙂

I suspect there would be more work involved than just #397 (or #345, #355, #360, #368, #369, #377, or #388), but I'm not sure.

**Comment by cy6erskunk** [comment]
Node.js 8 reached EOL in December 2019, and Eslint officially dropped support for it in Eslint 7 which makes [update PR](https://github.com/prettier/prettier-eslint/pull/397) fail

**Comment by chrisbobbe** [comment]
> Node.js 8 reached EOL in December 2019, and Eslint officially dropped support for it in Eslint 7 which makes [update PR](https://github.com/prettier/prettier-eslint/pull/397) fail

Mmm, OK. `prettier-eslint` specifies the preferred Node version in `"engines"` in `package.json`; I think it should be doable to just bump that from `">=8.0.0"` to, e.g., `">=10.0.0"`?

**Comment by chrisbobbe** [comment]
There's another thing blocking this, though; `eslint-config-kentcdodds` doesn't support ESLint 7 yet. That is expressed by the following peer dependency warning, even at its current latest, v14.16.0:

```
warning "eslint-config-kentcdodds > eslint-plugin-testing-library@3.8.0" has incorrect peer dependency "eslint@^5 || ^6".
```

`eslint-plugin-testing-library` has ESLint 7 support in progress, at https://github.com/testing-library/eslint-plugin-testing-library/pull/139.

**Comment by kylemh** [comment]
@hamzahamidi do we want to make a decision regarding moving to ESLint 7 and disallowing `<=node@^8`?

**Comment by hamzahamidi** [comment]
I'm ok with that too. The next versions will only support <=node@^8

**Comment by kylemh** [comment]
Well, the only tests failing on the PRs you listed are the ones using Node 8! So, it very well could be easy and just work.

I think we're open to a PR that:
- adjusts the `engines` field in `package.json` accordingly (only look for a floor please, not a ceiling)
- remove tests for Node 8 and add them for Node 14
- update ESLint to latest version

**Comment by chrisbobbe** [comment]
#407 has been merged, fixing this, so I'll go ahead and close. Thanks, @cy6erskunk, @hamzahamidi, and @zimme! 🎉
