### ISSUE TITLE
ESLint integration does not work

### ISSUE THREAD

**Issue by dgcoffman** [prettier/prettier-eslint#43]
Enabling ESlint integration in settings and then formatting a JS file does not cause eslint --fix to be run.

Using linter-eslint's format-on-save _does_ cause eslint --fix to transform my code as expected.

I have lint rules in `.eslintrc.yml` with eslint `npm install`ed. 

`node_modules/eslint/bin/eslint.js --fix tab.js` does the same thing as saving the file `tab.js` and letting linter-eslint format it.

Can anyone advise?

**Comment by kentcdodds** [comment]
Hi @dgcoffman,
Please file this issue on the [`prettier-atom`](https://github.com/jlongster/prettier-atom) repo. If you could provide a small git repository where you see this issue that would be very helpful. Thanks.
