### ISSUE TITLE
quiet option to no report error when eslint config not found or errors thrown

### ISSUE THREAD

**Issue by GopherJ** [prettier/prettier-eslint#474]
**Versions**:

- `prettier-eslint` version: `^11.0.0`
- `node` version: `12.19.0`
- `npm` (or `yarn`) version: `6.14.8`

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

 https://github.com/neoclide/coc-prettier/blob/master/src/PrettierEditProvider.ts#L215 
https://github.com/prettier/prettier-eslint/blob/master/src/index.js#L203
https://github.com/prettier/prettier-eslint/blob/master/src/index.js#L170

**What I did:**
I use coc.nvim & coc-prettier, coc-prettier provides `eslintIntegration ` option which uses this package, but this package reports errors when eslint config not found, I'm wondering if it's possible to add a config to disable the error reporting. Like `quiet` option.

because it's annoying to see the following error after saving file. I'm not able to disable coc-prettier and eslintintegration because some projects need it

![image](https://user-images.githubusercontent.com/33961674/102699338-20c62d00-4244-11eb-844c-7f4383e144bc.png)

**What happened:**

![image](https://user-images.githubusercontent.com/33961674/102699338-20c62d00-4244-11eb-844c-7f4383e144bc.png)
![image](https://user-images.githubusercontent.com/33961674/103171737-e6195180-484e-11eb-9a68-6ad70fa207c8.png)

**Reproduction repository:**

**Problem description:**

**Suggested solution:**
add quiet option

**Comment by GopherJ** [comment]
Or is it possible to have another logLevel which quiet everything? So that it can be more comfortable to use prettier-eslint in coc.nvim

**Comment by GopherJ** [comment]
any idea on this?

**Comment by JounQin** [comment]
PR welcome

**Comment by JounQin** [comment]
question: does ESLint support this functionality
