### ISSUE TITLE
prettier-eslint on vue file for multiline-ternary issue

### ISSUE THREAD

**Issue by basaran** [prettier/prettier-eslint#493]
**Versions**:

- `prettier-eslint` version: 5.0.0
- `node` version: v14.6.0
- `npm` (or `yarn`) version: 1.22.5

**Relevant code or config**

```javascript
isSetGet(file, "hello") ? "okay" : "never",
```

**What I did:**

I'm using the `prettier-eslint` with `vue` files and having a problem with enabling a specific rule `"multiline-ternary": ["error", "always"]`.

If I run `eslint` on the `vue` file, it formats the ternary statement properly.

If I run `prettier-eslint` on the `vue` file, it removes formatting as `prettier` would do, but `eslint` later would not format it.

When I ran `prettier-eslint` with `debug`, I saw this:

```
      "multiline-ternary": Array [
        "off",
      ],
```

Besides the normal rule for ternary, I also tried overrides with no luck in `.eslintrc.js`

```
overrides: [
        {
            files: ["*.vue"],
            rules: {
                "multiline-ternary": ["error", "always"],
            },
        },
    ],
```

My plugin and parser config is as follows:

```
    extends: ["eslint:recommended", "plugin:vue/base"],
    parserOptions: {
        parser: "babel-eslint",
    },
```

I am not sure why the `eslint` itself works properly, and why the `eslint-prettier` somehow overwrites my ternary rule. I know it's reading my rules because the infamous `"space-in-parens": ["error", "always"]"` formats just fine. I get space in parens after prettier formatting through eslint.

Is there something I can do to troubleshoot this?

**Comment by JounQin** [comment]
https://antfu.me/posts/why-reproductions-are-required

Feel free to comment to provide a minimal but runnable reproduction.
