### ISSUE TITLE
Remove rules that aren't fixable

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier-eslint#5]
Each rule you add to the ESLint config adds overhead. If it's not fixable then it's not useful overhead. We should improve perf by removing any rules from the config that aren't fixable. I'm not sure whether it's possible to know, but if it is, we should try. Could really speed things up I think.

**Comment by kentcdodds** [comment]
ping @gyandeeps, I think you could shed some light here :)

**Comment by gyandeeps** [comment]
Well this could get tricky because if the user sets the `useEslintrc` option then you have to do a lot of work (which i think is not worth it). 
So I would say visit this when we actually see an issue.

**Comment by exdeniz** [comment]
What we do with new rules or rules that will fixable in the future?

**Comment by kentcdodds** [comment]
Yeah, we'd probably want a way to dynamically identify rules that are fixable. If there's a way to do that. Somehow the eslint website knows, but I'm not sure whether that's manually maintained or not.

**Comment by exdeniz** [comment]
In JS rules file:
```
module.exports = {
    meta: {
        docs: {
            description: "require or disallow semicolons instead of ASI",
            category: "Stylistic Issues",
            recommended: false
        },

        fixable: "code",
...
```
but parse everytime repo.... and how deal with plugin?

**Comment by kentcdodds** [comment]
Now that the atom plugin and the CLI are working well, I've applied them to all three prettier-eslint related projects and I've gotta say that it could be handy to have things be a tad bit faster. On files over 100 lines, perf issues are slight, but noticeable. Anyone willing to throw their hat into making prettier-eslint faster, please be my guest!

**Comment by zimme** [comment]
The whole purpose of the tool is to automatically format your files. Running through prettier first and then eslint with `--fix`.

If you only want lint errors printed then using eslint with eslint-plugin-prettier will give you linting errors based on prettier too.

**Comment by theTechie** [comment]
@zimme - sorry for not being very clear. I lost my point after rephrasing a previous question :-)

I was thinking about providing an option to pick the rules which can be autofixed (even if it can be autofixed by eslint). Basically, having an option to get errors on some and autofix some.

Not sure if eslint already supports something similar ?

**Comment by kentcdodds** [comment]
I think this would be covered by: https://github.com/prettier/prettier-eslint/issues/118

Want to move discussion to that?
