### ISSUE TITLE
Make eslintConfig the same way as prettierOptions

### ISSUE THREAD

**Issue by sheerun** [prettier/prettier-eslint#50]
i.e. it <strike>should</strike> could provide just the defaults if filePath is provided.

It's in the same spirit as "You can also provide some of the options and have the remaining options derived via your eslint config.", but for eslint config, not prettier config.

**Comment by sheerun** [comment]
My use case: configuring prettier-eslint with some defaults, but allow user to override them in .eslintconfig

**Comment by kentcdodds** [comment]
Sounds good to me! Thanks for bringing it up! Anyone can feel free to [make a pull request](http://makeapullrequest.com)
