### ISSUE TITLE
Can you support Svelte?

### ISSUE THREAD

**Issue by NoelJacob** [prettier/prettier-eslint#525]

**Comment by basaran** [comment]
You need to provide more information, whether you are using the CLI or an editor extension. That being said, Svelte SFCs are the same as `vue` that is if you move your markup to `<template></template>` and set the `prettier.config.js` `parser` to `vue` for `*.svelte`.

**Comment by JounQin** [comment]
Did you try https://github.com/sveltejs/prettier-plugin-svelte?

**Comment by robertheessels** [comment]
I created a pull request for Svelte files: https://github.com/prettier/prettier-eslint/pull/950
