### ISSUE TITLE
semi rule doesn't work in React Classes

### ISSUE THREAD

**Issue by artembloom** [prettier/prettier-eslint#56]
Hi!

Even if I have ` "semi": ["error", "never"] ` rule in .eslintrc prettier adds semi in the end of state and arrow functions in React Classes like this

```
class Example extends React.Component {
  
  state = { imageLoading: true };

  onImageLoadStart = () => this.setState({ imageLoading: true });

  onImageLoadEnd = () => this.setState({ imageLoading: false });

  render() {
    // some code
  }
}
```

It seems this is a bug

**Comment by kentcdodds** [comment]
Please see https://github.com/prettier/prettier-eslint/issues/32

TL;DR, you need to use `eslint-plugin-babel`'s `babel/semi` rule instead of ESLint's `semi` rule.

Good luck :)
