### ISSUE TITLE
Option to Run Prettier Last

### ISSUE THREAD

**Issue by spudly** [prettier/prettier-eslint#58]
I've adopted a strategy of using eslint to catch errors, but prettier to enforce style. Because of this strategy, I'd really rather run prettier *after* `eslint --fix`. This would give prettier the final say on how the code should be styled.

It would be great if there was an option (`--prettier-last` maybe?) that would run prettier *after* running eslint.

If needed, I could work on the pull request. I just want to make sure it would be accepted before I start working on it.

**Comment by kentcdodds** [comment]
Sure! Feel free to add the option to this repo and then a flag to [the CLI](https://github.com/prettier/prettier-eslint-cli/blob/master/src/parser.js) (use it [here](https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L60) and [here](https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L175)), and then an option to the [atom plugin](https://github.com/prettier/prettier-atom/blob/master/src/config-schema.json) (use it [here](https://github.com/prettier/prettier-atom/blob/master/src/executePrettier.js#L31)).

Thanks!

**Comment by JounQin** [comment]
@spudly @kentcdodds 

Sorry, I'm a bit confusing here. You can always be able to implement this feature without 3rd-party tool/cli by `eslint filePath && prettier --write filePath` or `eslint-plugin-prettier` and the performance should be better. I'm not sure why you use `prettier-eslint` at all?
