### ISSUE TITLE
indentation in HTML file not working

### ISSUE THREAD

**Issue by Qythyx** [prettier/prettier-eslint#618]
**Versions**:

- `prettier-eslint` version: 12.0.0
- `node` version: v12.22.6
- `npm` (or `yarn`) version: 6.14.15

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```html
<body>
    <script>
        const text = 'very ... very long text';
    </script>
...
</body>
```

**What I did:**

using the rule:

```
        "operator-linebreak": [
            "error",
            "before"
        ]
```

`eslint.js --fix file.html`

**What happened:**

The text was formatted as:

```html
<body>
    <script>
        const text
 = 'very ... very long text';
    </script>
...
</body>
```

but I expected it to be indented as in:

```html
<body>
    <script>
        const text
            = 'very ... very long text';
    </script>
...
</body>
```

**Problem description:**

Indentation doesn't seem to work. I believe this is limited to the situations when the Javascript is embedded in a HTML file and it works correctly in a .js file.

**Suggested solution:**

The HTML indentation should be taken into account.

**Comment by JounQin** [comment]
https://antfu.me/posts/why-reproductions-are-required

Feel free to comment to provide a minimal but runnable reproduction.
