### ISSUE TITLE
Prettier-eslint is not paying attention to eslint max-len rule configured per file

### ISSUE THREAD

**Issue by anback** [prettier/prettier-eslint#62]
Hi!

Super great work with eslint-prettier! Lovin it!

See screenshot. When i configure the max-len rule like this atom-prettier does not care. It does work when i configure a max-len rule in .eslintrc.

With "work" i mean it respects the max-len rule and format the code accordingly

![image](https://cloud.githubusercontent.com/assets/2440382/24580781/a48216aa-170e-11e7-8e87-ad287517ffc8.png)

**Comment by kentcdodds** [comment]
I'm unsure of what could cause this. Could you dig a little deeper using [the logging capabilities](https://github.com/prettier/prettier-eslint#loglevel-enum-trace-debug-info-warn-error-silent)?

If you have the atom plugin, then, you could pop open the developer tools and set `process.env.LOG_LEVEL` to `trace` or `debug` before you do any formatting. That's a pretty easy way to do this.

Let us know what you find.

**Comment by jortizsao** [comment]
Hi, same issue here. I'm using the eslint-airbnb rules that comes with a max-len of 100, and prettier-eslint is not respecting the rule. i.e It keeps the line as it is with 102 characters.

![screen shot 2017-05-02 at 12 07 19](https://cloud.githubusercontent.com/assets/13261810/25613852/0ad80a66-2f30-11e7-8d9c-f7d0f751a323.png)

See attached log from prettier-eslint in trace mode
[prettier-eslint_log.txt](https://github.com/prettier/prettier-eslint/files/970124/prettier-eslint_log.txt)

Thanks!

**Comment by kentcdodds** [comment]
That's a pretty big log 😀 would probably be easier to try to reproduce it with a single smaller file. Also, I probably won't have time to do any more than review a [pull request](http://makeapullrequest.com) (which I'm happy to do). I don't have enough time to provide much support! Sorry, and good luck!

**Comment by lukaszmoroz** [comment]
The problem is probably that prettier-eslint only reads the eslint config to set options for prettier, which reformats the line to fit the default 80 characters, and eslint can't fix it back.

**Comment by kentcdodds** [comment]
Ah, yeah, that's a known issue. Sorry, we can't fix that 😞
