### ISSUE TITLE
Audit Fail due to an used package

### ISSUE THREAD

**Issue by santhoshsk1918** [prettier/prettier-eslint#643]
**Versions**:

- `prettier-eslint` version: 13.0.0
- `node` version: 12.14.1

**Problem description:**
Audit is failing due to package used pretty-format 

<img width="931" alt="Screenshot 2021-10-13 at 4 12 26 AM" src="https://user-images.githubusercontent.com/11382648/137038685-ab037264-f202-44cd-acd2-b79e4b01b932.png">

**Suggested solution:**
update package.json

**Comment by internalsystemerror** [comment]
The earliest patched version of `ansi-regex` is `5.0.1`. This is fixed in `pretty-format` >= `25.1.0` (which requires ansi-regex `^5.0.0`).

**Comment by dfrankes** [comment]
Any updates on this? My CICD is failing because of this issue.

**Comment by Towerism** [comment]
In the meantime, my team has been using https://github.com/IBM/audit-ci.
The tool allows us to continue auditing our dependencies as part of our CICD pipeline, but we can allow certain advisories so they don't cause the pipeline to fail.

**Comment by heath-freenome** [comment]
My company is ALSO concerned about this vulnerability. Is it possible to switch to using something other than the `now archived` `loglevel-colored-level-prefix` tool that is locked in on a very old `chalk`?

**Comment by zmagauina-fn** [comment]
@kentcdodds do you know of an alternative to your now archived `loglevel-colored-level-prefix` library that I can use to make a PR to remove this issue?

**Comment by kentcdodds** [comment]
I'm afraid no.

**Comment by jenniferabowd** [comment]
@kentcdodds would it be worth converting this over to using Chalk? Or maybe removing this package and functionality so it will not have a color? I'm happy to do this if you would like.
