### ISSUE TITLE
It doesn't work with eslint v8

### ISSUE THREAD

**Issue by vingeraycn** [prettier/prettier-eslint#656]
**Versions**:

- `prettier-eslint` version: 9.0.2
- `node` version: 14
- `npm` (or `yarn`) version: 1.22.5

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```shell
prettier-eslint '**/*.{ts,tsx}' --list-different
```

**What I did:**

**What happened:**
![image](https://user-images.githubusercontent.com/19839331/139210561-d2f8b4d1-06c0-4dca-8637-1f480de0899f.png)

**Reproduction repository:**

**Problem description:**
It doesn't work with eslint v8

**Suggested solution:**
update with [this document](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#remove-cliengine) to adapting eslint v8.

**Comment by pjg** [comment]
Dropping here a related issue in coc-eslint for reference: https://github.com/neoclide/coc-eslint/pull/118

**Comment by talko-cervello** [comment]
Any updates?

**Comment by shellscape** [comment]
@kylemh thanks for taking this on. Is there any chance you can ping the part of the team in charge of prettier-atom? That's failing hard and they need an update.

**Comment by idahogurl** [comment]
@shellscape I'm not sure if the Prettier team works on any repo besides prettier. Kyle and I are just contributors on this project. With Atom being sunsetted on December 15, 2022, I don't think there will be further development on prettier-atom https://github.blog/2022-06-08-sunsetting-atom/

I suggest you move to another editor like VS Code. I made the switch years ago and I still run the Atom keyboard layout.

**Comment by shellscape** [comment]
Thanks for the reply. I'm waiting for Zed to mature and currently beta testing. I _loathe_ VSCode. In the mean time, since `prettier-atom` is not being maintained and we do have until December this year, would be it possible to add a contributor that can keep it up to date? I'm happy to run my own fork but there's a community still out there in need.

**Comment by idahogurl** [comment]
@shellscape All someone needs to do is create a PR and then tag or message someone marked as a Collaborator to get it reviewed, merged, and deployed. That's what I did to become a collaborator. 

P.S. I still miss Atom.

**Comment by shellscape** [comment]
@idahogurl we've tried. it's sat idle. https://github.com/prettier/prettier-atom/pull/1271

**Comment by kylemh** [comment]
While we're collaborators in `prettier-eslint`, we're not collaborators in `prettier-atom` and have no way of pushing it forward for you.

**Comment by shellscape** [comment]
@kylemh understood. Shared that in the hopes that it might be passed onto other teams or core team members. is there a private prettier slack, discord, or mailing list for the teams that you could help out the community by sharing this situation? we're coming up against crickets on the outside over here.

**Comment by kylemh** [comment]
There is not. We're a random collection of people that do what we can, when we can.

**Comment by shellscape** [comment]
Man, that's a bummer. Even on the webpack core team we had mechanisms for other non-core individual teams and groups of collabs to talk to one another. I would have thought the Prettier org would be more organized given how huge the project is within the developer community these days. But thanks for the clarification.

> Your solution may need to be forking it and fixing it yourself.

Way ahead of you. But that doesn't mean that I'm not going to stop trying to help the larger Atom community.
