### ISSUE TITLE
Shoudn't format file when only prettier can process file

### ISSUE THREAD

**Issue by sheerun** [prettier/prettier-eslint#68]
If file has non-standard syntax, like class properties, prettier-eslint passes source through prettier but silently skips transforming through eslint. This behavior makes file to be formatted with default prettier settings, while the expected behavior is leaving file intact.

Example file:

```jsx
import React from 'react';

class Example extends React.Component {
  state = {
    foo: 'bar'
  }
  
  render() {
    return <div foo='bar'></div>
  }
}
```

if you format this with prettier-eslint rules set to 

```jsx
{
  quotes: [
    'error',
    'single',
    {avoidEscape: true, allowTemplateLiterals: true}
  ],
  'jsx-quotes': ['error', 'prefer-single'],
}
```

the jsx is formatted to double quotes

**Comment by kentcdodds** [comment]
Hmmmmm... Are you sure that's what's happening? If you look at the source code, you'll see that it throws an error if prettier or eslint fail.

If it is a problem, feel free to open a pull request to fix it. Thanks!

**Comment by sheerun** [comment]
I'm sure only about the result, maybe it happens because of some other reason

**Comment by kentcdodds** [comment]
Any chance you could make a repo that reproduces the issue?

**Comment by sheerun** [comment]
It's no longer an issue for me, I ended up configuring babel-eslint parser so any syntax babel recognizes is possible. You might consider the same for prettier-eslint-cli: https://github.com/sheerun/prettier-standard/commit/eea070e836edf73e12c9479caa0a3e11e269a029

**Comment by kentcdodds** [comment]
Thanks for sharing. I think it's not an issue for prettier-eslint because people configure ESLint with the parser that works for their code. So if they're using ESNext code that ESLint doesn't support, they'll specify they want to use the babel-eslint parser and that's what we'll use.

Cheers.
