### ISSUE TITLE
"comma-dangle": [2, "always-multiline"] should not add trailing commas to function arguments

### ISSUE THREAD

**Issue by echenley** [prettier/prettier-eslint#69]
http://eslint.org/docs/rules/comma-dangle#options

According to the eslint docs, "always-multiline" ignores functions by default. I believe that means that prettier-eslint should set prettier's `--trailing-comma` option to `es5` rather than `all`, unless `functions: "always"` is specified in eslint.

Relevant eslint config:

```
{
  "rules": {
    "comma-dangle": [2, "always-multiline"],
  }
}
```

Prettier command:
```
prettier --single-quote --no-semi --trailing-comma es5
```

Unformatted:
```js
function someFunction(longParamater1, longParamater2, longParamater3, longParamater4) {
  return ''
}
```

Prettier + `eslint --fix` output:
```js
function someFunction(
  longParamater1,
  longParamater2,
  longParamater3,
  longParamater4 // no comma
) {
  return ''
}
```

Prettier-eslint output:

```js
function someFunction(
  longParamater1,
  longParamater2,
  longParamater3,
  longParamater4, // comma
) {
  return ''
}
```

Edit:
It is possible to fix it using `prettier-eslint --prettier.trailing-comma es5`, but those options aren't available when using prettier-atom.

**Comment by kentcdodds** [comment]
Thanks for digging into this. Could you look into submitting a pull request?

**Comment by kentcdodds** [comment]
[Here's the code that should change](https://github.com/prettier/prettier-eslint/blob/master/src/utils.js#L156-L173), [here's where you'd add a test case](https://github.com/prettier/prettier-eslint/blob/master/src/utils.test.js#L170), [here's a free course on how to contribute to OSS](http://makeapullrequest.com/) (if you're new to contributing), and [here's our CONTRIBUTING.md](https://github.com/prettier/prettier-eslint/blob/master/CONTRIBUTING.md).

Cheers!

**Comment by enriquecaballero** [comment]
I'm still having this issue. I don't think PR#71 fixes this.

**Comment by kentcdodds** [comment]
Thanks for reaching out @enriquecaballero. Could you [make a pull request](http://makeapullrequest.com) to fix the issue you're seeing?

**Comment by enriquecaballero** [comment]
I would, but there seems to be some confusion here as to what the expected behavior is for this issue. The Prettier README defaults trailing commas to "none" and quotes default to false, meaning no single quotes turned on by default. Yet, for some reason, when I use Prettier via Atom, that uses `prettier-eslint`, whenever the ESLint Integration box is checked, I don't have this problem. It's only when I use the `prettier-eslint-cli` that turns on single quotes and trailing commas by default. I would assume it should be the other way around? One should expect Prettier defaults to apply? It doesn't make sense to turn them on one-by-one. Also, I don't know if this is a `eslint-prettier` issue or an `eslint-prettier-cli` issue.

**Comment by echenley** [comment]
@enriquecaballero Are you trying to get trailing commas for all function arguments? If so, you need to set your eslint config to:

```json
{
  "rules": {
    "comma-dangle": [2, {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "always-multiline",
    }]
  }
}
```

Either of the following will give you trailing commas for everything EXCEPT functions:

```json
{
  "rules": {
    "comma-dangle": [2, "always-multiline"]
  }
}

// OR

{
  "rules": {
    "comma-dangle": [2, {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "ignore",
    }]
  }
}
```

Pretty sure setting this in your eslintrc should get you the same results for both prettier-eslint and prettier-eslint-cli. Could be wrong though.

**Comment by enriquecaballero** [comment]
@echenley All I'm trying to understand is why `prettier-eslint-cli`'s defaults aren't matching either Prettier's or ESLint's. Like I said in my earlier comment, Prettier defaults trailing commas to "never" and single quotes to false. ESLint's comma-dangle rule defaults to "never". It just feels like prettier-eslint-cli is overriding Prettier whenever those rules aren't set. To get comma-dangles to work, I have to do do `prettier-eslint ―prettier.trailingComma none` which shouldn't be the case.

**Comment by enriquecaballero** [comment]
@echenley It just seems that `prettier-eslint-cli` and `prettier-atom` use `prettier-eslint` differently. `prettier-atom` has Prettier's defaults correctly set up, but `prettier-eslint-cli` does not.

**Comment by enriquecaballero** [comment]
I think I understand now. When you install `prettier-atom`, in its settings it provides the Prettier "defaults" correctly, as you can see below:

<img width="500" alt="screen shot 2017-05-09 at 9 12 08 pm" src="https://cloud.githubusercontent.com/assets/7918284/25878953/84291ad2-34fc-11e7-9d6d-88635daced00.png">

`prettier-atom` depends on that form to create internal defaults:

```
// prettier-atom/src/options.js
trailingComma: getPrettierOption('trailingComma')

// prettier-atom/src/helpers.js
const getConfigOption = (key: string) => atom.config.get(`prettier-atom.${key}`);
```

Here's what I'm running into:

Using `prettier-eslint-cli` : `prettier-eslint --write "src/**/*.@(js|jsx)"`
```javascript
const test = [
  'hello',
  'world',
  'hello',
  'world',
  'hello',
  'world',
  'hello',
  'world',
  'hello',
  'world',
];
```

Using `prettier-atom` with ESLint Integration enabled and the settings from the image above:
```javascript
const test = [
  "hello",
  "world",
  "hello",
  "world",
  "hello",
  "world",
  "hello",
  "world",
  "hello",
  "world"
];
```

**Comment by kentcdodds** [comment]
Thanks for digging further. What do you propose?

**Comment by enriquecaballero** [comment]
I found the problem. The defaultValue param's are not matching Prettier's defaults in these lines:
- https://github.com/prettier/prettier-eslint/blob/master/src/utils.js#L198 (should be `false`)
- https://github.com/prettier/prettier-eslint/blob/master/src/utils.js#L215 (should be 'none') 
- https://github.com/prettier/prettier-eslint/blob/master/src/utils.js#L243 (should be `true`)
Working on a PR now.

**Comment by kentcdodds** [comment]
Ah! Nice, thanks for looking into that. A PR will be accepted. Now to decide whether this should be a breaking change or not... 🤔 

I think it wont be. Things are a little tricky with this package 🙃

**Comment by cbrwizard** [comment]
Any updates on this?
