### ISSUE TITLE
Integration with CI/CD (gitlab)

### ISSUE THREAD

**Issue by michelgokan** [prettier/prettier-eslint#716]
Is there any command that I can validate/check if formatting standard has been implemented based on BOTH eslint AND prettier formatting rules using this plugin? For example, in case there are conflicting changes in eslint (with prettier), `eslint --format` can only check if the code is formatted according to eslint formatting rules, and running `prettier` can only check if the code is passing the prettier formatting rules, but there is no command that can check both (including the conflicting changes). In this scenario, if I run eslint first and prettier next, it will pass the eslint but will fail prettier, and if run prettier first and eslint next, eslint will fail and prettier will pass.

I'm wondering if there is any way I can validate the code based on all rulesets (considering the conflicting ones too).

**Comment by JounQin** [comment]
Maybe you want https://github.com/prettier/eslint-plugin-prettier
