### ISSUE TITLE
Custom Fallback Options if a Setting is Not Inferrable from ESlint

### ISSUE THREAD

**Issue by robwise** [prettier/prettier-eslint#72]
This is, admittedly, purely needed for prettier-atom. In prettier-atom, if you turn ESlint integration on, it's going to stay on regardless of whether the project you've got open actually has all prettier-related rules set in their config. 

If the project doesn't have an ESlint rule needed for prettier, users are wanting to fall back to the prettier setting they've set inside of their prettier-atom config instead of falling back to the default value for that prettier option (which is how it currently works if I'm not mistaken). If I could pass fall-back options to prettier-eslint when using it to format, that would be great. Note that this is different than the current API which only allows manual overrides as opposed to fall-backs.

Any thoughts on adding this to the API?

**Comment by kentcdodds** [comment]
I think this is great. What if we did added `prettierFallbackOptions`? Then we could use that [here](https://github.com/prettier/prettier-eslint/blob/849b25a4b648bf9664e9053588b8deb6d55ce6ce/src/utils.js#L117-L140). I _think_ that it would be based on whether the value is `RULE_DISABLED` then we'd use the fallback. Maybe @briandipalma can weigh in here with a suggestion.

But in any case, I'd be thrilled to accept a PR for this. I would love this functionality myself!

**Comment by robwise** [comment]
I'm looking at the code and trying to figure out where it would go, I think `RULE_DISABLED` is only when the rule is set to `0` or `off`. If the rule can't be found in ESlint, it seems to be supplied a default value when calling `getRuleValue`: https://github.com/prettier/prettier-eslint/blob/849b25a4b648bf9664e9053588b8deb6d55ce6ce/src/utils.js#L204

I'm not totally sure how I'd hook in here

**Comment by kentcdodds** [comment]
Right [here](https://github.com/prettier/prettier-eslint/blob/849b25a4b648bf9664e9053588b8deb6d55ce6ce/src/utils.js#L231-L236) we log if the rule's not been configured. Actually if you pop open Atom devtools and enter: `process.env.LOG_LEVEL = 'trace'` then run format it'll give you a lot of handy info, like this:

<img width="886" alt="screen shot 2017-04-21 at 8 20 23 pm" src="https://cloud.githubusercontent.com/assets/1500684/25300600/00dac692-26d0-11e7-991b-78721f9fd15a.png">

That might be helpful...
