### ISSUE TITLE
Rules no-var and prefer-const not being fixed

### ISSUE THREAD

**Issue by lukaszmoroz** [prettier/prettier-eslint#82]
**Versions**:

- `prettier-eslint` version: 6.2.1
- `node` version: v7.10.0
- `yarn` version: 0.23.4

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```yaml
# .eslintrc.yaml
env:
  es6: true
rules:
  prefer-const: error
  no-var: error
```

```javascript
const format = require("prettier-eslint")
const text = `
  let x = 0
  var y = 0
`
console.log(format({ text }))
```

**What happened:**

```javascript
let x = 0
var y = 0
```

**What should happen:**

```javascript
const x = 0
const y = 0
```

**Problem description:**

These rules are ignored by `prettier-eslint` because of [this variable](https://github.com/prettier/prettier-eslint/blob/fa37803347f4f2b9cf63ac5e408a6f83e12e17eb/src/utils.js#L72), which removes rules that are not fixable. But these two are!

If I add them inline, everything works:
```javascript
const text = `
  /* eslint "prefer-const": "error" */
  /* eslint "no-var": "error" */
  let x = 0
  var y = 0
`
```

**Suggested solution:**

For a start, remove these rules from the array.
In future, don't make too big assumptions on whether a rule will never be fixable (someone may use an older version of `prettier-eslint` with a never version of `eslint` and come across this problem).

**Comment by kentcdodds** [comment]
Sounds great! Could you [make a pull request](http://makeapullrequest.com) to fix that? Thanks!
