### ISSUE TITLE
`prettier-eslint` command fails due to unknown environment key `jest/globals`

### ISSUE THREAD

**Issue by tommy-mitchell** [prettier/prettier-eslint#853]
**Versions**:

- `prettier-eslint` version: 15.0.1
- `node` version: 18.8.0
- `npm` (or `yarn`) version: 8.18.0 (`npm`), 1.22.19 (`yarn`)

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```javascript
// .eslintrc.js
const config = {
  extends: ['kentcdodds', 'kentcdodds/jest'], // includes "jest/globals"
  // ...
};
```

**What I did:**

Ran `yarn start format` in a local copy of the `prettier-eslint` repo.

**What happened:**

The command (`prettier-eslint "**/*.{js,json,md,yml}" ".eslintrc.js" --write`) fails on all JS files with the following error message:

<details>
<summary>Error Message</summary>

```sh
prettier-eslint [ERROR]: eslint fix failed due to an eslint error
prettier-eslint-cli [ERROR]: There was an error formatting "~\prettier-eslint\*.js": 
    Error: CLIOptions:
        Environment key "jest/globals" is unknown

        at ~\prettier-eslint\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2058:23
        at Array.forEach (<anonymous>)
        at ConfigValidator.validateEnvironment (~\prettier-eslint\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2052:34)
        at ConfigValidator.validateConfigArray (~\prettier-eslint\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2202:18)
        at CascadingConfigArrayFactory._finalizeConfigArray (~\prettier-eslint\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3962:23)
        at CascadingConfigArrayFactory.getConfigArrayForFile (~\prettier-eslint\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3768:21)
        at CLIEngine.isPathIgnored (~\prettier-eslint\node_modules\eslint\lib\cli-engine\cli-engine.js:989:18)
        at CLIEngine.executeOnText (~\prettier-eslint\node_modules\eslint\lib\cli-engine\cli-engine.js:899:38)
        at ESLint.lintText (~\prettier-eslint\node_modules\eslint\lib\eslint\eslint.js:593:23)
        at eslintFix (~\prettier-eslint\node_modules\@prettier\eslint\dist\index.js:180:35)
```
</details>

**Reproduction repository:**

N/A

**Problem description:**

I'm attempting to set up `prettier-eslint` locally to make a PR, but trying to format the files fails with the above error. However, manually running `npx prettier "src/utils.js" --write && npx eslint "src/utils.js" --fix` produces no errors (in addition, the ESLint extension in my editor has no issues linting, either). For some reason, this problem is specific to `prettier-eslint`. I can reproduce this on my Windows 10 desktop and my MacBook Pro Ventura laptop.

**Suggested solution:**

I'm pretty stumped. I know that the `jest` plugin is being included from the extended `kentcdodds/jest` config, so I'm not sure why the environment key is unknown.

**Comment by tommy-mitchell** [comment]
Turns out `jest` now needs to be `@jest` in the config. Closing this to open a PR in https://github.com/kentcdodds/eslint-config-kentcdodds.

**Comment by tommy-mitchell** [comment]
Reopening this because the problem still seems to be with `prettier-eslint`. If I change `jest.js` in the config to have the `@jest/globals` key, `prettier-eslint` works, but then ESLint breaks as *it* can’t find the new environment key. Removing the `@` reverses the problem.

Maybe somehow it’s version mismatch between the two tools? I’m using VSCode extensions for them, which is where the error messages are being reported. I’m on mobile but I can check later.

**Comment by idahogurl** [comment]
@tommy-mitchell I had the same issue and what I ended up doing in my `.eslintrc.js` file

```
overrides: [
    {
      // enable eslint-plugin-testing-library for matching testing files
      files: ['**/?(*.)+(spec|test).[jt]s?(x)'],
      extends: ['plugin:jest/recommended'],
    },
  ]
  ```
