### ISSUE TITLE
Shebang being stripped when run with eslint-plugin-node

### ISSUE THREAD

**Issue by lukaszmoroz** [prettier/prettier-eslint#86]
**Versions**:

- `prettier-eslint` version: 6.2.2
- `node` version: v7.10.0
- `yarn` version: 0.24.5

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**

```javascript
// package.json
"bin": { "bin": "index.js" }
```

```javascript
// index.js
#!/usr/bin/env node
console.log("Hello, world!");
```

```yaml
# .eslintrc.yaml
plugins: [node]
rules: { node/shebang: error }
```

https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/shebang.md
When run with `eslint --fix`, the shebang is correctly added if absent and not removed.
When run with `prettier`, it's not touched at all.
And `prettier-eslint` keeps removing it (but only if the `node/shebang` rule is enabled).
It seems that the rule can't detect if the script is a bin file, i.e. can't read `package.json` or something, so it treats the file as a regular file.

**Comment by kentcdodds** [comment]
Hmmm... Interesting. I'm not sure what would cause that :-( Could you make a repository that reproduces this?

**Comment by lukaszmoroz** [comment]
https://github.com/lukaszmoroz/test-shebang

**Comment by kentcdodds** [comment]
Looks like an ESLint bug: https://github.com/lukaszmoroz/test-shebang/pull/1

I'll let you report this over there. Good luck!

**Comment by lukaszmoroz** [comment]
Oh, so `prettier-eslint` reads the file and runs it through `executeOnText`.
`node/shebang` needs to know which file it is run on to check if the file is in `package.json` `bin` field.
[`executeOnText`](http://eslint.org/docs/developer-guide/nodejs-api#executeontext) takes a second parameter that sets the filename.
See: https://github.com/lukaszmoroz/test-shebang/commit/0d5b078b53214b78b24c47f3ac07411107daff38

**Comment by kentcdodds** [comment]
Ah! Nice! Yeah, this is a prettier-eslint issue then! Woo! Thanks for digging into that. Could you [Make a pull request](http://makeapullrequest.com) to make that happen?
