### ISSUE TITLE
.eslintrc.* not supported

### ISSUE THREAD

**Issue by therealklanni** [prettier/prettier-eslint#89]
**Versions**:

- `prettier-eslint` version: ^6.2.1
- `prettier-atom` version: 0.31.1
- `atom` version: 
  ```
  Atom    : 1.17.0
  Electron: 1.3.15
  Chrome  : 52.0.2743.82
  Node    : 6.5.0
  ```

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

No (it's being used in prettier-atom)

**What I did:**

I have a project with the spec-compliant ESLint config filename, such as `.eslintrc.json5`

**What happened:**

The config is not loaded by prettier-atom (prettier-eslint)

**Suggested solution:**

Ensure prettier-eslint is able to load `.eslintrc.*` configs.

**Comment by therealklanni** [comment]
Sorry, accidentally hit CMD-enter, still editing description

**Comment by kentcdodds** [comment]
> Have you followed the debugging tips?
> No (it's being used in prettier-atom)

Please read the debugging tips. They talk about how to debug with atom.

**Comment by kentcdodds** [comment]
Also, thanks for the report. I hope we can figure out what's going on :)

**Comment by therealklanni** [comment]
Sorry, I skimmed the tips, but I must not have seen the Atom stuff. Will look into it.

**Comment by therealklanni** [comment]
OK, I took another look following the debugging tips. I don't know what I must be doing wrong, but it doesn't seem to log any debug messages.

- I renamed my config back to .eslintrc.json and completely quit Atom and restarted it.
- Showing some of my eslint rules
- Showing that my JS file doesn't match the rules (has semi colons and semi is disabled in both prettier and eslint)
- Save file to trigger prettier-atom (no errors)
- Changed some more stuff around trying to force an eslint error (still nothing)
- Save (still nothing)
- Nothing being logged in console

![](http://g.recordit.co/BOugIGi6On.gif)

**Comment by kentcdodds** [comment]
Hmmm... Are you sure you have format on save enabled? You could also try formatting from the menu.

**Comment by kentcdodds** [comment]
Oh, also make sure you have eslint integration checked

**Comment by therealklanni** [comment]
Disregard this issue. I tried dis/re-enabling it and now it's working. False alarm, sorry.

**Comment by kentcdodds** [comment]
Glad you got it working

**Comment by cbranch101** [comment]
I think this might still be an issue,  In the debug messages, I'm seeing the built in eslint config from CRA, but none of my custom rules.  It works if I use a standard eslintrc file, but but not if its a JS file

**Comment by cbranch101** [comment]
Nevermind, I hadn't installed the right packages in the project, we're good
