### ISSUE TITLE
Improve errors handling in config resolution

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier-eslint#90]
I'm using this in context of VSCode (via [prettier-eslint-code](https://github.com/RobinMalfait/prettier-eslint-code)), at some point eslint config resolution stopped working (empty config was resolved internally)

The problem lies here: [src/index.js#L206-L209](https://github.com/prettier/prettier-eslint/blob/fee640478679d954f90175df32bdaaef3cfb33fd/src/index.js#L206-L209) Whatever error occurs during config resolution it just without backing reason states that no config could be found, and resolves with empty one.

It'll be way better if eventual errors are recognized, and are either rethrown or accurate actions are taken to errors that are understood.

In my case it appeared that some other VSCode extension crashed and it was its error that prevented proper config resolution, if package would just rethrow this error, then on my end the cause would be immediately exposed.

**Comment by kentcdodds** [comment]
Ah yes! Happy to accept [a pull request](http://makeapullrequest.com) to make that better :+1:

**Comment by interactivellama** [comment]
I'm dealing this too, makes me wonder if the quick fix is to run eslint first for code quality and let it error out if the config is bad, then run `prettier-eslint`.

What's the suggested behavior/API for this? It will ignore eslint and go on with prettier by itself UNLESS there is an explicit config setting? If there is an eslint config settings file and it's invalid then error out?

Just adding some details/questions.

Current lint scripts:
```
"lint:docs": "./node_modules/.bin/prettylint \"*.md\"",
"lint:fix": "./node_modules/.bin/prettier-eslint --write \"**/*.{js,jsx}\" && ./node_modules/.bin/prettylint \"*.json\" --fix",
"lint:quality": "./node_modules/.bin/eslint \"**/*.{js,jsx,json}\" --max-warnings=0",
"lint:style": "./node_modules/.bin/prettier-eslint --list-different \"**/*.{js,jsx}\" && ./node_modules/.bin/prettylint \"*.json\"",
```
