### ISSUE TITLE
tslint support?

### ISSUE THREAD

**Issue by KurtPreston** [prettier/prettier-eslint#92]
I really like the idea of this project, but use TypeScript and tslint.  Would it be in scope of this project to add tslint support, or would you recommend I fork instead?

**Comment by kentcdodds** [comment]
I've thought about that (especially when we added the CSS "support" which was basically just skip eslint for that step).

I'm not totally opposed to including TSLint support. So long as someone else is committed to helping maintain it because I don't use TSLint at all. Would you like to do that?

**Comment by zimme** [comment]
Should this package really support `tslint`? Wouldn't it be better to have a separate package `prettier-tslint` for that`. What I could see this package support is `eslint` with [`typescript-eslint-parser`](https://github.com/eslint/typescript-eslint-parser), now that prettier supports typescript.

**Comment by kentcdodds** [comment]
Yeah, I'm in favor of that @zimme :+1:

**Comment by zimme** [comment]
Having `prettier-eslint` and `prettier-tslint` as separate package would hopefully keep the complexity down a bit, and and nothing is stopping the maintainers from working together where it makes sense. Some logic might be sharable with a common package?

**Comment by kentcdodds** [comment]
To be quite honest, I'm only barely hanging onto this package myself. I've got a lot of things pulling at my time, so if someone wanted to help collaborate on a tslint version of this package, I'm afraid that I couldn't do much by way of support there. Would love it if someone else wanted to join in and help maintain things...

**Comment by zimme** [comment]
I'm spread quite thin myself, I am however starting on a project using typescript and are looking into how to use prettier and tslint together and if I don't find a better way I'll probably be open to give `prettier-tslint` a shoot. Other than that I'm using this package in quite a few projects and I've become a bit familiar with the codebase so I could try and help out a bit.

**Comment by zimme** [comment]
Since v7.1.0 this package support ts files using prettier nd eslint with typescript-eslint-parser. #121

**Comment by zimme** [comment]
Since we're supporting typescript now by using `typescript-eslint-parser`, the same parser `prettier` is using for it's typescript support, I'm closing this issue.

I don't feel that this package should support tslint, but it belongs in another package `prettier-tslint`. If enought people :-1: this comment I can think about reopening the issue.

**Comment by azz** [comment]
`prettier-tslint` should definitely be a separate package. I've just started work on it here: https://github.com/azz/prettier-tslint

Super basic support is done. Given an input file it will:

* Run `prettier --write`
* Locate `tslint.json`
* Run `tslint --fix`

Currently there are some intermediary writes to disk but I'll be working to fix that soon.
