### ISSUE TITLE
Shouldn't this be the other way around? "This formats your code via prettier, and then passes the result of that to eslint --fix."

### ISSUE THREAD

**Issue by DanKaplanSES** [prettier/prettier-eslint#945]
**Versions**:

- `prettier-eslint` version: n/a
- `node` version: v18.17.1
- `npm` (or `yarn`) version: 9.6.7

This is more of a question or documentation request than a bug. The readme says,

> This formats your code via prettier, and then passes the result of that to eslint --fix.

Wouldn't it make more sense to run `eslint --fix` THEN `prettier` instead of the other way around? My use case is [the curly rule](https://eslint.org/docs/latest/rules/curly). `eslint --fix` will change

```js
if (foo) foo++;
```

to

```js
if (foo) {foo++};
```

and `prettier` will change it to this:

```js
if (foo) {
  foo++
};
```

I may not be exactly right on the specifics of the formatting, but my point is that `eslint --fix` adds the curly braces and `prettier` formats them. If `prettier` runs first, the code will be left in this state:

```js
if (foo) {foo++};
```

and, on a second run, the code will change again to this:

```js
if (foo) {
  foo++
};
```

Is [the curly rule](https://eslint.org/docs/latest/rules/curly) a weird edge case, am I misinterpreting this repo's documentation, or am I confused in some other way?

**Comment by JounQin** [comment]
https://github.com/prettier/prettier-eslint?tab=readme-ov-file#prettierlast-boolean

Please read document more carefully.

**Comment by DanKaplanSES** [comment]
@JounQin Thank you for the link. When you say, "And people using this tool prefer prettier but with some exception and want to leave it to ESLint fixing," do you mean people using this tool prefer to overwrite prettier's formatting changes with ESLint's formatting changes?

**Comment by JounQin** [comment]
Yes, and that's why this tool is made for.

**Comment by JounQin** [comment]
Maybe we should rerun the flow until the formatting is stable.

**Comment by DanKaplanSES** [comment]
> Yes, and that's why this tool is made for.

Thanks for the explanation. Are you aware [all the eslint formatting options will soon be deprecated](https://eslint.org/blog/2023/10/deprecating-formatting-rules/)?

**Comment by JounQin** [comment]
See https://github.com/eslint-stylistic/eslint-stylistic
