### ISSUE TITLE
Status of capturing eslint warnings/errors?

### ISSUE THREAD

**Issue by gwhitney** [prettier/prettier-eslint#946]
In the past, I filed issue #704 requesting the ability to capture eslint warnings/errors (currently they are simply discarded by the code), as it would make workflow on a project that I am on significantly smoother. The response to the issue was PR welcome. I supplied PR #827 (albeit after some delay), which was approved for merging. However, the PR was never merged, and the issue was closed with no other response or resolution. Are the prettier-eslint maintainers willing to add a feature that allows capturing such information? If so, how might I facilitate that? Thanks for any information.

**Comment by JounQin** [comment]
Thanks for reminding, I just reopened related issue and PR, and will help to rebase when I'm free.
