### ISSUE TITLE
Infers trailing comma as none when ESLint comma-dangle is set to always-multiline

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-eslint#96]
When `comma-dangle` has a value of `always-multiline`, prettier-eslint incorrectly infers the `trailing-comma` option to `none`: https://github.com/prettier/prettier-eslint/blob/de44a0a277afb3ec73bdf4e32a354d3d516f8d91/src/utils.js#L199.

Can we update it to infer either `es5` or `all`?

**Comment by kentcdodds** [comment]
Yes! Would you like to [make a pull request](http://makeapullrequest.com)?

**Comment by OliverJAsh** [comment]
I would be more than happy to do that, but wanted to discuss it first. What do you think the correct behaviour is? Set it to `es5` or `all`?

**Comment by kentcdodds** [comment]
I think `es5` works. We shouldn't want to add commas in function parameter lists and calls in this case I think (based on the eslint docs). Thanks!
