### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by rantiev** [prettier/prettier-eslint#960]
Reading docs i have no clue on how to use this npm module. Is it a cli, or should it run manually?
Should i create a node script which connect each file and runs this module format + analyze on them? 

Looks like some wet solution.

**Comment by JounQin** [comment]
For API: https://github.com/prettier/prettier-eslint?tab=readme-ov-file#usage

For cli, it's a seperate npm package: https://github.com/prettier/prettier-eslint-cli?tab=readme-ov-file#usage
