### ISSUE TITLE
Fallbacks don't work for disabled rules

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-eslint#97]
Given a disabled ESLint rule, e.g.

```
max-len: 0
```

… and a fallback setting, e.g.

```
printWidth: 200
```

The fallback setting will not be honoured.

Example:

``` js
const prettierEslint = require('prettier-eslint');

const filePath = 'foo.js';
const text = `
const x = { foobarbazfoobarbazfoobarbazfoobarbazfoobarbazfoobarfoobarbaz: "foobarbazfoobarbazfoobarbaz" }`;
const result = prettierEslint({
  text,
  filePath,
  fallbackPrettierOptions: {
    printWidth: 200,
  },
});

console.log(result);
```

Actual result:

```
❯ node prettier-eslint-test.js
const x = {
  foobarbazfoobarbazfoobarbazfoobarbazfoobarbazfoobarfoobarbaz:
    'foobarbazfoobarbazfoobarbaz',
};
```

Expected result:

```
const x = { foobarbazfoobarbazfoobarbazfoobarbazfoobarbazfoobarfoobarbaz: 'foobarbazfoobarbazfoobarbaz' };
```

I expected this to stay on one line, because of the `printWidth: 200`.

**Comment by OliverJAsh** [comment]
This appears to occur because we don't use the fallbacks if the rule is disabled: https://github.com/prettier/prettier-eslint/blob/de44a0a277afb3ec73bdf4e32a354d3d516f8d91/src/utils.js#L151

**Comment by kentcdodds** [comment]
I suppose what you say makes sense. Happy to accept a pull request for it! Thanks!

**Comment by OliverJAsh** [comment]
I opened a PR: https://github.com/prettier/prettier-eslint/pull/98
